=begin
#eCF-Pronesoft Master Integration API

#Especificación de producción **200% detallada** de la API de eCF-Pronesoft. **Optimizada para la generación de SDKs de alta fidelidad.**  Esta especificación es el resultado de una auditoría exhaustiva del código fuente (NestJS), cubriendo el 100% de los DTOs, validaciones con regex, esquemas de Webhooks y  flujos de seguridad OAuth 2.0. 

The version of the OpenAPI document: 1.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PronesoftEcf::DocumentStatusChangedPayload
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PronesoftEcf::DocumentStatusChangedPayload do
  #let(:instance) { PronesoftEcf::DocumentStatusChangedPayload.new }

  describe 'test an instance of DocumentStatusChangedPayload' do
    it 'should create an instance of DocumentStatusChangedPayload' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PronesoftEcf::DocumentStatusChangedPayload)
    end
  end

  describe 'test attribute "encf"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "dgii_message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
