# coding: utf-8

"""
    eCF-Pronesoft Master Integration API

    **Highly detailed** production-grade API specification for eCF-Pronesoft. **Optimized for high-fidelity SDK generation.**  This specification is the result of an exhaustive audit of the source code (NestJS), covering 100% of the DTOs, regex validations, Webhook schemas, and  OAuth 2.0 security flows. 

    The version of the OpenAPI document: 0.0.1
    Contact: contacto@pronesoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pronesoft_ecf.models.tax_sequence import TaxSequence

class TestTaxSequence(unittest.TestCase):
    """TaxSequence unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaxSequence:
        """Test TaxSequence
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaxSequence`
        """
        model = TaxSequence()
        if include_optional:
            return TaxSequence(
                id = '',
                type = '',
                next_number = ''
            )
        else:
            return TaxSequence(
        )
        """

    def testTaxSequence(self):
        """Test TaxSequence"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
