# coding: utf-8

"""
    eCF-Pronesoft Integration API

    ## Descripción general API de nivel productivo para emitir Comprobantes Fiscales Electrónicos (e-CF) en la República Dominicana a través de la plataforma Pronesoft.  ## Autenticación — OAuth 2.0 Client Credentials  ### Pasos 1. Obtén tus credenciales desde el portal:    - Sandbox: https://ecf.sandbox.pronesoft.com → Apps → Default Sandbox App    - Producción: https://ecf.pronesoft.com → Integraciones → Apps → Crear App 2. Solicita un token via POST /oauth/token — válido por 24 horas (86400s). 3. Usa: Authorization: Bearer <accessToken> en cada request. 4. Renueva al recibir HTTP 401. Buena práctica: renovar 5 minutos antes del vencimiento.  ### Delegación multi-empresa Para actuar en nombre de una empresa asociada (sucursal), agrega:   x-tenant-id: <business-uuid> NO envíes x-tenant-id cuando actúes como la empresa principal.  ### Detalles del Sandbox - Usa cualquier RNC que comience con SBX (ej. SBX123456) — no se requiere certificado real. - Las secuencias son automáticas — no es necesario crearlas manualmente. - El campo environment en el cuerpo del documento DEBE ser TesteCF.  ### Scopes disponibles business:read, business:create, business:update, members:read, members:invite, members:revoke, certificates:read, certificates:upload, certificates:update, documents:read, documents:create, documents:send, documents:receive, documents:update, approvals:read, approvals:commercial, sequences:read, sequences:create, sequences:update, sequences:cancel, business_info:read, certification:read, certification:write, reports:read 

    The version of the OpenAPI document: 1.2.0
    Contact: support@pronesoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pronesoft_ecf.models.webhook_notification_payload_data import WebhookNotificationPayloadData

class TestWebhookNotificationPayloadData(unittest.TestCase):
    """WebhookNotificationPayloadData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookNotificationPayloadData:
        """Test WebhookNotificationPayloadData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookNotificationPayloadData`
        """
        model = WebhookNotificationPayloadData()
        if include_optional:
            return WebhookNotificationPayloadData(
                document_id = '550e8400-e29b-41d4-a716-446655440000',
                encf = 'E310000000001',
                issuer_rnc = '133190907',
                status = 'COMPLETED',
                legal_status = 'ACCEPTED',
                document_type = '31',
                track_id = '',
                dgii_message = '',
                sender_rnc = '123456789',
                receiver_rnc = '133190907',
                total_amount = 1500.5,
                issue_date = '2025-06-04T10:30Z',
                received_at = '2025-06-04T14:30Z',
                rejection_reason = 'Error de Firma Digital',
                error_code = 'SCHEMA_VALIDATION_FAILED',
                message = 'El campo FechaVencimientoSecuencia es requerido',
                reason = 'Secuencias no utilizadas',
                retry_at = '2025-01-15T13:00Z',
                approval_status = 'approved',
                approval_date = '2025-06-04T14:35Z',
                rejection_code = '',
                rejection_description = '',
                expiration_date = '2025-02-10T00:00Z',
                days_left = 15,
                ip = '192.168.1.100',
                user_agent = 'Chrome/120',
                city = 'Santo Domingo',
                app_id = 'app_abc123',
                rotated_at = '2025-01-15T10:00Z',
                usage_percent = 90,
                remaining_docs = 150,
                invoice_id = 'inv_abc123',
                amount = 4500.0,
                pdf_url = 'https://storage.ecf.pronesoft.com/invoices/inv_abc123.pdf',
                sequence_type = 'E31',
                remaining = 50,
                alert_level = 'danger',
                voided_range = 'E310000000100-E310000000200',
                branch_id = 'branch_abc123',
                rnc = '133190907',
                name = 'Sucursal Norte SRL',
                new_status = 'ACTIVE',
                email = 'removido@empresa.com',
                role = 'VIEWER',
                invited_by = 'admin@empresa.com',
                user_id = 'usr_abc123',
                joined_at = '2025-01-15T10:00Z',
                removed_by = 'admin@empresa.com',
                process_id = 'abc123',
                business_name = 'Mi Empresa SRL',
                download_url = 'https://...',
                completed_at = '2025-01-15T16:00Z'
            )
        else:
            return WebhookNotificationPayloadData(
                document_id = '550e8400-e29b-41d4-a716-446655440000',
                encf = 'E310000000001',
                issuer_rnc = '133190907',
                status = 'COMPLETED',
                sender_rnc = '123456789',
                receiver_rnc = '133190907',
                total_amount = 1500.5,
                issue_date = '2025-06-04T10:30Z',
                received_at = '2025-06-04T14:30Z',
                error_code = 'SCHEMA_VALIDATION_FAILED',
                message = 'El campo FechaVencimientoSecuencia es requerido',
                reason = 'Secuencias no utilizadas',
                approval_status = 'approved',
                approval_date = '2025-06-04T14:35Z',
                expiration_date = '2025-02-10T00:00Z',
                days_left = 15,
                ip = '192.168.1.100',
                user_agent = 'Chrome/120',
                app_id = 'app_abc123',
                rotated_at = '2025-01-15T10:00Z',
                usage_percent = 90,
                remaining_docs = 150,
                invoice_id = 'inv_abc123',
                amount = 4500.0,
                pdf_url = 'https://storage.ecf.pronesoft.com/invoices/inv_abc123.pdf',
                sequence_type = 'E31',
                remaining = 50,
                alert_level = 'danger',
                voided_range = 'E310000000100-E310000000200',
                branch_id = 'branch_abc123',
                rnc = '133190907',
                name = 'Sucursal Norte SRL',
                new_status = 'ACTIVE',
                email = 'removido@empresa.com',
                role = 'VIEWER',
                invited_by = 'admin@empresa.com',
                user_id = 'usr_abc123',
                joined_at = '2025-01-15T10:00Z',
                removed_by = 'admin@empresa.com',
                process_id = 'abc123',
                business_name = 'Mi Empresa SRL',
                completed_at = '2025-01-15T16:00Z',
        )
        """

    def testWebhookNotificationPayloadData(self):
        """Test WebhookNotificationPayloadData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
