# coding: utf-8

"""
    eCF-Pronesoft Master Integration API

    Especificación de producción 100% exacta de la API de eCF-Pronesoft. **Diseñada para la generación automática de SDKs.**  Esta especificación ha sido auditada contra el código fuente real (DTOs, Controllers y Guards),  reflejando con total precisión la obligatoriedad de los campos y las estructuras de respuesta. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pronesoft_ecf.models.mining_info import MiningInfo

class TestMiningInfo(unittest.TestCase):
    """MiningInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MiningInfo:
        """Test MiningInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MiningInfo`
        """
        model = MiningInfo()
        if include_optional:
            return MiningInfo(
                net_weight_kg = 1.337,
                net_weight_mining = 1.337,
                affiliation_type = '1',
                settlement = '1'
            )
        else:
            return MiningInfo(
        )
        """

    def testMiningInfo(self):
        """Test MiningInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
