/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.pronesoft.ecf.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.pronesoft.ecf.models.EcfHistoryItem
import com.pronesoft.ecf.models.DocumentStatus
import com.pronesoft.ecf.models.Environment
import com.pronesoft.ecf.models.ProcessingLog

class EcfHistoryItemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EcfHistoryItem
        //val modelInstance = EcfHistoryItem()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `trackId`
        should("test trackId") {
            // uncomment below to test the property
            //modelInstance.trackId shouldBe ("TODO")
        }

        // to test the property `encf`
        should("test encf") {
            // uncomment below to test the property
            //modelInstance.encf shouldBe ("TODO")
        }

        // to test the property `documentType`
        should("test documentType") {
            // uncomment below to test the property
            //modelInstance.documentType shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `rnc`
        should("test rnc") {
            // uncomment below to test the property
            //modelInstance.rnc shouldBe ("TODO")
        }

        // to test the property `environment`
        should("test environment") {
            // uncomment below to test the property
            //modelInstance.environment shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `logs`
        should("test logs") {
            // uncomment below to test the property
            //modelInstance.logs shouldBe ("TODO")
        }

    }
}
