/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.pronesoft.ecf.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.pronesoft.ecf.models.ItemAlternativeCurrency

class ItemAlternativeCurrencyTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ItemAlternativeCurrency
        //val modelInstance = ItemAlternativeCurrency()

        // to test the property `unitPrice`
        should("test unitPrice") {
            // uncomment below to test the property
            //modelInstance.unitPrice shouldBe ("TODO")
        }

        // to test the property `discount`
        should("test discount") {
            // uncomment below to test the property
            //modelInstance.discount shouldBe ("TODO")
        }

        // to test the property `surcharge`
        should("test surcharge") {
            // uncomment below to test the property
            //modelInstance.surcharge shouldBe ("TODO")
        }

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

    }
}
