/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.pronesoft.ecf.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.pronesoft.ecf.models.Page

class PageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Page
        //val modelInstance = Page()

        // to test the property `pageNumber`
        should("test pageNumber") {
            // uncomment below to test the property
            //modelInstance.pageNumber shouldBe ("TODO")
        }

        // to test the property `lineFrom`
        should("test lineFrom") {
            // uncomment below to test the property
            //modelInstance.lineFrom shouldBe ("TODO")
        }

        // to test the property `lineTo`
        should("test lineTo") {
            // uncomment below to test the property
            //modelInstance.lineTo shouldBe ("TODO")
        }

        // to test the property `subtotal`
        should("test subtotal") {
            // uncomment below to test the property
            //modelInstance.subtotal shouldBe ("TODO")
        }

    }
}
