=begin
#eCF-Pronesoft Integration API

### Overview Production-grade API for issuing Electronic Tax Receipts (e-CF) in the Dominican Republic through the Pronesoft platform.  ## Authentication — OAuth 2.0 Client Credentials  ### Steps 1. Get credentials from the portal:    - Sandbox: https://ecf.sandbox.pronesoft.com -> Apps -> Default Sandbox App    - Production: https://ecf.pronesoft.com -> Integrations -> Apps -> Create App 2. Request a token via POST /oauth/token — valid for 24 hours (86400s). 3. Use: Authorization: Bearer <accessToken> on every request. 4. Renew on HTTP 401. Best practice: renew 5 minutes before expiry.  ### Multi-company delegation To act on behalf of an associated company (branch), add:   x-tenant-id: <business-uuid> Do NOT send x-tenant-id when acting as the main company.  ### Sandbox specifics - Use any RNC starting with SBX (e.g. SBX123456) — no real certificate needed. - Sequences are automatic — no need to create them manually. - The environment field in the document body MUST be TesteCF.  ### Scopes business:read, business:create, business:update, members:read, members:invite, members:revoke, certificates:read, certificates:upload, certificates:update, documents:read, documents:create, documents:send, documents:receive, documents:update, approvals:read, approvals:commercial, sequences:read, sequences:create, sequences:update, sequences:cancel, business_info:read, certification:read, certification:write, reports:read 

The version of the OpenAPI document: 1.1.0
Contact: support@pronesoft.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

# Common files
require 'pronesoft_ecf/api_client'
require 'pronesoft_ecf/api_error'
require 'pronesoft_ecf/api_model_base'
require 'pronesoft_ecf/version'
require 'pronesoft_ecf/configuration'

# Models
require 'pronesoft_ecf/models/account_type'
require 'pronesoft_ecf/models/additional_info'
require 'pronesoft_ecf/models/alternative_currency'
require 'pronesoft_ecf/models/approval_item'
require 'pronesoft_ecf/models/approval_list_response'
require 'pronesoft_ecf/models/associated_company'
require 'pronesoft_ecf/models/associated_company_subscription'
require 'pronesoft_ecf/models/associated_company_subscription_plan'
require 'pronesoft_ecf/models/billing_indicator'
require 'pronesoft_ecf/models/buyer'
require 'pronesoft_ecf/models/certification_niche'
require 'pronesoft_ecf/models/certification_niche_niche_items_inner'
require 'pronesoft_ecf/models/certification_status'
require 'pronesoft_ecf/models/company_document_metrics'
require 'pronesoft_ecf/models/company_document_metrics_group_by_status_inner'
require 'pronesoft_ecf/models/company_document_metrics_group_by_status_inner_count'
require 'pronesoft_ecf/models/company_document_metrics_main_business'
require 'pronesoft_ecf/models/company_document_metrics_totals'
require 'pronesoft_ecf/models/company_metrics'
require 'pronesoft_ecf/models/company_metrics_documents_status'
require 'pronesoft_ecf/models/create_associated_company201_response'
require 'pronesoft_ecf/models/create_tax_sequence201_response'
require 'pronesoft_ecf/models/create_tax_sequence_request'
require 'pronesoft_ecf/models/delete_associated_company200_response'
require 'pronesoft_ecf/models/discount_or_surcharge'
require 'pronesoft_ecf/models/document_stats_response'
require 'pronesoft_ecf/models/document_status'
require 'pronesoft_ecf/models/ecf_history_item'
require 'pronesoft_ecf/models/ecf_stats_response'
require 'pronesoft_ecf/models/ecf_status_response'
require 'pronesoft_ecf/models/ecf_status_response_mensajes_inner'
require 'pronesoft_ecf/models/ecf_submission_response'
require 'pronesoft_ecf/models/ecf_submission_response_dgii_response'
require 'pronesoft_ecf/models/electronic_document'
require 'pronesoft_ecf/models/environment'
require 'pronesoft_ecf/models/error_response'
require 'pronesoft_ecf/models/get_next_number200_response'
require 'pronesoft_ecf/models/get_next_number200_response_data'
require 'pronesoft_ecf/models/invoice_type'
require 'pronesoft_ecf/models/invoice_type_sequence'
require 'pronesoft_ecf/models/item'
require 'pronesoft_ecf/models/item_additional_tax'
require 'pronesoft_ecf/models/item_alternative_currency'
require 'pronesoft_ecf/models/item_codes_inner'
require 'pronesoft_ecf/models/item_discount_inner'
require 'pronesoft_ecf/models/item_mining_info'
require 'pronesoft_ecf/models/list_tax_sequences200_response'
require 'pronesoft_ecf/models/o_auth_token_request'
require 'pronesoft_ecf/models/o_auth_token_response'
require 'pronesoft_ecf/models/page'
require 'pronesoft_ecf/models/pagination_meta'
require 'pronesoft_ecf/models/payment_form'
require 'pronesoft_ecf/models/payment_method'
require 'pronesoft_ecf/models/print_format'
require 'pronesoft_ecf/models/processing_log'
require 'pronesoft_ecf/models/rate_limit_error_response'
require 'pronesoft_ecf/models/received_document'
require 'pronesoft_ecf/models/received_document_list_response'
require 'pronesoft_ecf/models/received_document_stats_response'
require 'pronesoft_ecf/models/reference_info'
require 'pronesoft_ecf/models/sent_document_detail'
require 'pronesoft_ecf/models/sent_document_list_response'
require 'pronesoft_ecf/models/sent_document_summary'
require 'pronesoft_ecf/models/sent_document_summary_business'
require 'pronesoft_ecf/models/start_certification200_response'
require 'pronesoft_ecf/models/start_certification_request'
require 'pronesoft_ecf/models/subquantity'
require 'pronesoft_ecf/models/subtotal'
require 'pronesoft_ecf/models/tax_sequence'
require 'pronesoft_ecf/models/tax_sequence_created'
require 'pronesoft_ecf/models/totals'
require 'pronesoft_ecf/models/transport'
require 'pronesoft_ecf/models/update_tax_sequence_request'
require 'pronesoft_ecf/models/upload_certificate_response'
require 'pronesoft_ecf/models/void_tax_sequence200_response'
require 'pronesoft_ecf/models/void_tax_sequence200_response_data'
require 'pronesoft_ecf/models/void_tax_sequence_request'
require 'pronesoft_ecf/models/webhook_config_detail'
require 'pronesoft_ecf/models/webhook_config_response'
require 'pronesoft_ecf/models/webhook_event_type'
require 'pronesoft_ecf/models/webhook_notification_payload'
require 'pronesoft_ecf/models/webhook_stats'
require 'pronesoft_ecf/models/webhook_stats_stats'

# APIs
require 'pronesoft_ecf/api/associated_companies_api'
require 'pronesoft_ecf/api/authentication_api'
require 'pronesoft_ecf/api/automated_certification_api'
require 'pronesoft_ecf/api/commercial_approvals_api'
require 'pronesoft_ecf/api/digital_certificates_api'
require 'pronesoft_ecf/api/documents_received_api'
require 'pronesoft_ecf/api/documents_sent_api'
require 'pronesoft_ecf/api/ecf_submission_api'
require 'pronesoft_ecf/api/reports_api'
require 'pronesoft_ecf/api/tax_sequences_api'
require 'pronesoft_ecf/api/webhook_configuration_api'

module PronesoftEcf
  class << self
    # Customize default settings for the SDK using block.
    #   PronesoftEcf.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
