/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.pronesoft.ecf.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.pronesoft.ecf.models.CreateWebhookConfig
import com.pronesoft.ecf.models.WebhookConfigResponse

import com.squareup.moshi.Json

import com.pronesoft.ecf.infrastructure.ApiClient
import com.pronesoft.ecf.infrastructure.ApiResponse
import com.pronesoft.ecf.infrastructure.ClientException
import com.pronesoft.ecf.infrastructure.ClientError
import com.pronesoft.ecf.infrastructure.ServerException
import com.pronesoft.ecf.infrastructure.ServerError
import com.pronesoft.ecf.infrastructure.MultiValueMap
import com.pronesoft.ecf.infrastructure.PartConfig
import com.pronesoft.ecf.infrastructure.RequestConfig
import com.pronesoft.ecf.infrastructure.RequestMethod
import com.pronesoft.ecf.infrastructure.ResponseType
import com.pronesoft.ecf.infrastructure.Success
import com.pronesoft.ecf.infrastructure.toMultiValue

open class WebhookConfigurationApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.ecf.sandbox.pronesoft.com/api/v1")
        }
    }

    /**
     * POST /{rnc}/webhooks
     * Registrar nuevo webhook
     * 
     * @param rnc 
     * @param createWebhookConfig 
     * @return WebhookConfigResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createWebhook(rnc: kotlin.String, createWebhookConfig: CreateWebhookConfig) : WebhookConfigResponse {
        val localVarResponse = createWebhookWithHttpInfo(rnc = rnc, createWebhookConfig = createWebhookConfig)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as WebhookConfigResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /{rnc}/webhooks
     * Registrar nuevo webhook
     * 
     * @param rnc 
     * @param createWebhookConfig 
     * @return ApiResponse<WebhookConfigResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createWebhookWithHttpInfo(rnc: kotlin.String, createWebhookConfig: CreateWebhookConfig) : ApiResponse<WebhookConfigResponse?> {
        val localVariableConfig = createWebhookRequestConfig(rnc = rnc, createWebhookConfig = createWebhookConfig)

        return request<CreateWebhookConfig, WebhookConfigResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createWebhook
     *
     * @param rnc 
     * @param createWebhookConfig 
     * @return RequestConfig
     */
    fun createWebhookRequestConfig(rnc: kotlin.String, createWebhookConfig: CreateWebhookConfig) : RequestConfig<CreateWebhookConfig> {
        val localVariableBody = createWebhookConfig
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/{rnc}/webhooks".replace("{"+"rnc"+"}", encodeURIComponent(rnc.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /{rnc}/webhooks/{webhookId}
     * Eliminar configuración de webhook
     * 
     * @param rnc 
     * @param webhookId 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteWebhook(rnc: kotlin.String, webhookId: kotlin.String) : Unit {
        val localVarResponse = deleteWebhookWithHttpInfo(rnc = rnc, webhookId = webhookId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /{rnc}/webhooks/{webhookId}
     * Eliminar configuración de webhook
     * 
     * @param rnc 
     * @param webhookId 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteWebhookWithHttpInfo(rnc: kotlin.String, webhookId: kotlin.String) : ApiResponse<Unit?> {
        val localVariableConfig = deleteWebhookRequestConfig(rnc = rnc, webhookId = webhookId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteWebhook
     *
     * @param rnc 
     * @param webhookId 
     * @return RequestConfig
     */
    fun deleteWebhookRequestConfig(rnc: kotlin.String, webhookId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/{rnc}/webhooks/{webhookId}".replace("{"+"rnc"+"}", encodeURIComponent(rnc.toString())).replace("{"+"webhookId"+"}", encodeURIComponent(webhookId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /{rnc}/webhooks
     * Listar todas las configuraciones de webhooks
     * 
     * @param rnc 
     * @return kotlin.collections.List<WebhookConfigResponse>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listWebhooks(rnc: kotlin.String) : kotlin.collections.List<WebhookConfigResponse> {
        val localVarResponse = listWebhooksWithHttpInfo(rnc = rnc)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<WebhookConfigResponse>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /{rnc}/webhooks
     * Listar todas las configuraciones de webhooks
     * 
     * @param rnc 
     * @return ApiResponse<kotlin.collections.List<WebhookConfigResponse>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listWebhooksWithHttpInfo(rnc: kotlin.String) : ApiResponse<kotlin.collections.List<WebhookConfigResponse>?> {
        val localVariableConfig = listWebhooksRequestConfig(rnc = rnc)

        return request<Unit, kotlin.collections.List<WebhookConfigResponse>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listWebhooks
     *
     * @param rnc 
     * @return RequestConfig
     */
    fun listWebhooksRequestConfig(rnc: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/{rnc}/webhooks".replace("{"+"rnc"+"}", encodeURIComponent(rnc.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
