/*
 * eCF-Pronesoft Integration API
 *
 * ## Descripción general API de nivel productivo para emitir Comprobantes Fiscales Electrónicos (e-CF) en la República Dominicana a través de la plataforma Pronesoft.  ## Autenticación — OAuth 2.0 Client Credentials  ### Pasos 1. Obtén tus credenciales desde el portal:    - Sandbox: https://ecf.sandbox.pronesoft.com → Apps → Default Sandbox App    - Producción: https://ecf.pronesoft.com → Integraciones → Apps → Crear App 2. Solicita un token via POST /oauth/token — válido por 24 horas (86400s). 3. Usa: Authorization: Bearer <accessToken> en cada request. 4. Renueva al recibir HTTP 401. Buena práctica: renovar 5 minutos antes del vencimiento.  ### Delegación multi-empresa Para actuar en nombre de una empresa asociada (sucursal), agrega:   x-tenant-id: <business-uuid> NO envíes x-tenant-id cuando actúes como la empresa principal.  ### Detalles del Sandbox - Usa cualquier RNC que comience con SBX (ej. SBX123456) — no se requiere certificado real. - Las secuencias son automáticas — no es necesario crearlas manualmente. - El campo environment en el cuerpo del documento DEBE ser TesteCF.  ### Scopes disponibles business:read, business:create, business:update, members:read, members:invite, members:revoke, certificates:read, certificates:upload, certificates:update, documents:read, documents:create, documents:send, documents:receive, documents:update, approvals:read, approvals:commercial, sequences:read, sequences:create, sequences:update, sequences:cancel, business_info:read, certification:read, certification:write, reports:read 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@pronesoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Pronesoft.Ecf.Sdk.Client;
using Pronesoft.Ecf.Sdk.Model;

namespace Pronesoft.Ecf.Sdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDigitalCertificatesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Subir certificado digital (P12/PFX)
        /// </summary>
        /// <remarks>
        /// Sube el certificado de firma digital emitido por DGII para una empresa. Se almacena cifrado con AES-256-CBC. No existe endpoint de descarga. Tip Sandbox: Los RNC con prefijo SBX no requieren certificado. 
        /// </remarks>
        /// <exception cref="Pronesoft.Ecf.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rnc">RNC de la empresa (9 u 11 dígitos). En Sandbox usar valores con prefijo SBX.</param>
        /// <param name="file">Archivo del certificado en formato .p12 o .pfx.</param>
        /// <param name="password">Contraseña para desbloquear el certificado.</param>
        /// <returns>UploadCertificateResponse</returns>
        UploadCertificateResponse UploadCertificate(string rnc, FileParameter file, string password);

        /// <summary>
        /// Subir certificado digital (P12/PFX)
        /// </summary>
        /// <remarks>
        /// Sube el certificado de firma digital emitido por DGII para una empresa. Se almacena cifrado con AES-256-CBC. No existe endpoint de descarga. Tip Sandbox: Los RNC con prefijo SBX no requieren certificado. 
        /// </remarks>
        /// <exception cref="Pronesoft.Ecf.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rnc">RNC de la empresa (9 u 11 dígitos). En Sandbox usar valores con prefijo SBX.</param>
        /// <param name="file">Archivo del certificado en formato .p12 o .pfx.</param>
        /// <param name="password">Contraseña para desbloquear el certificado.</param>
        /// <returns>ApiResponse of UploadCertificateResponse</returns>
        ApiResponse<UploadCertificateResponse> UploadCertificateWithHttpInfo(string rnc, FileParameter file, string password);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDigitalCertificatesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Subir certificado digital (P12/PFX)
        /// </summary>
        /// <remarks>
        /// Sube el certificado de firma digital emitido por DGII para una empresa. Se almacena cifrado con AES-256-CBC. No existe endpoint de descarga. Tip Sandbox: Los RNC con prefijo SBX no requieren certificado. 
        /// </remarks>
        /// <exception cref="Pronesoft.Ecf.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rnc">RNC de la empresa (9 u 11 dígitos). En Sandbox usar valores con prefijo SBX.</param>
        /// <param name="file">Archivo del certificado en formato .p12 o .pfx.</param>
        /// <param name="password">Contraseña para desbloquear el certificado.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UploadCertificateResponse</returns>
        System.Threading.Tasks.Task<UploadCertificateResponse> UploadCertificateAsync(string rnc, FileParameter file, string password, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Subir certificado digital (P12/PFX)
        /// </summary>
        /// <remarks>
        /// Sube el certificado de firma digital emitido por DGII para una empresa. Se almacena cifrado con AES-256-CBC. No existe endpoint de descarga. Tip Sandbox: Los RNC con prefijo SBX no requieren certificado. 
        /// </remarks>
        /// <exception cref="Pronesoft.Ecf.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rnc">RNC de la empresa (9 u 11 dígitos). En Sandbox usar valores con prefijo SBX.</param>
        /// <param name="file">Archivo del certificado en formato .p12 o .pfx.</param>
        /// <param name="password">Contraseña para desbloquear el certificado.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UploadCertificateResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<UploadCertificateResponse>> UploadCertificateWithHttpInfoAsync(string rnc, FileParameter file, string password, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDigitalCertificatesApi : IDigitalCertificatesApiSync, IDigitalCertificatesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DigitalCertificatesApi : IDisposable, IDigitalCertificatesApi
    {
        private Pronesoft.Ecf.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DigitalCertificatesApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public DigitalCertificatesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DigitalCertificatesApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public DigitalCertificatesApi(string basePath)
        {
            this.Configuration = Pronesoft.Ecf.Sdk.Client.Configuration.MergeConfigurations(
                Pronesoft.Ecf.Sdk.Client.GlobalConfiguration.Instance,
                new Pronesoft.Ecf.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Pronesoft.Ecf.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Pronesoft.Ecf.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DigitalCertificatesApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public DigitalCertificatesApi(Pronesoft.Ecf.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Pronesoft.Ecf.Sdk.Client.Configuration.MergeConfigurations(
                Pronesoft.Ecf.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Pronesoft.Ecf.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Pronesoft.Ecf.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DigitalCertificatesApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DigitalCertificatesApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DigitalCertificatesApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DigitalCertificatesApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Pronesoft.Ecf.Sdk.Client.Configuration.MergeConfigurations(
                Pronesoft.Ecf.Sdk.Client.GlobalConfiguration.Instance,
                new Pronesoft.Ecf.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Pronesoft.Ecf.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Pronesoft.Ecf.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DigitalCertificatesApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DigitalCertificatesApi(HttpClient client, Pronesoft.Ecf.Sdk.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Pronesoft.Ecf.Sdk.Client.Configuration.MergeConfigurations(
                Pronesoft.Ecf.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Pronesoft.Ecf.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Pronesoft.Ecf.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DigitalCertificatesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public DigitalCertificatesApi(Pronesoft.Ecf.Sdk.Client.ISynchronousClient client, Pronesoft.Ecf.Sdk.Client.IAsynchronousClient asyncClient, Pronesoft.Ecf.Sdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Pronesoft.Ecf.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Pronesoft.Ecf.Sdk.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Pronesoft.Ecf.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Pronesoft.Ecf.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Pronesoft.Ecf.Sdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Pronesoft.Ecf.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Subir certificado digital (P12/PFX) Sube el certificado de firma digital emitido por DGII para una empresa. Se almacena cifrado con AES-256-CBC. No existe endpoint de descarga. Tip Sandbox: Los RNC con prefijo SBX no requieren certificado. 
        /// </summary>
        /// <exception cref="Pronesoft.Ecf.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rnc">RNC de la empresa (9 u 11 dígitos). En Sandbox usar valores con prefijo SBX.</param>
        /// <param name="file">Archivo del certificado en formato .p12 o .pfx.</param>
        /// <param name="password">Contraseña para desbloquear el certificado.</param>
        /// <returns>UploadCertificateResponse</returns>
        public UploadCertificateResponse UploadCertificate(string rnc, FileParameter file, string password)
        {
            Pronesoft.Ecf.Sdk.Client.ApiResponse<UploadCertificateResponse> localVarResponse = UploadCertificateWithHttpInfo(rnc, file, password);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Subir certificado digital (P12/PFX) Sube el certificado de firma digital emitido por DGII para una empresa. Se almacena cifrado con AES-256-CBC. No existe endpoint de descarga. Tip Sandbox: Los RNC con prefijo SBX no requieren certificado. 
        /// </summary>
        /// <exception cref="Pronesoft.Ecf.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rnc">RNC de la empresa (9 u 11 dígitos). En Sandbox usar valores con prefijo SBX.</param>
        /// <param name="file">Archivo del certificado en formato .p12 o .pfx.</param>
        /// <param name="password">Contraseña para desbloquear el certificado.</param>
        /// <returns>ApiResponse of UploadCertificateResponse</returns>
        public Pronesoft.Ecf.Sdk.Client.ApiResponse<UploadCertificateResponse> UploadCertificateWithHttpInfo(string rnc, FileParameter file, string password)
        {
            // verify the required parameter 'rnc' is set
            if (rnc == null)
                throw new Pronesoft.Ecf.Sdk.Client.ApiException(400, "Missing required parameter 'rnc' when calling DigitalCertificatesApi->UploadCertificate");

            // verify the required parameter 'file' is set
            if (file == null)
                throw new Pronesoft.Ecf.Sdk.Client.ApiException(400, "Missing required parameter 'file' when calling DigitalCertificatesApi->UploadCertificate");

            // verify the required parameter 'password' is set
            if (password == null)
                throw new Pronesoft.Ecf.Sdk.Client.ApiException(400, "Missing required parameter 'password' when calling DigitalCertificatesApi->UploadCertificate");

            Pronesoft.Ecf.Sdk.Client.RequestOptions localVarRequestOptions = new Pronesoft.Ecf.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Pronesoft.Ecf.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Pronesoft.Ecf.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("rnc", Pronesoft.Ecf.Sdk.Client.ClientUtils.ParameterToString(rnc)); // path parameter
            localVarRequestOptions.FileParameters.Add("file", file);
            localVarRequestOptions.FormParameters.Add("password", Pronesoft.Ecf.Sdk.Client.ClientUtils.ParameterToString(password)); // form parameter

            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<UploadCertificateResponse>("/{rnc}/certificates", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UploadCertificate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Subir certificado digital (P12/PFX) Sube el certificado de firma digital emitido por DGII para una empresa. Se almacena cifrado con AES-256-CBC. No existe endpoint de descarga. Tip Sandbox: Los RNC con prefijo SBX no requieren certificado. 
        /// </summary>
        /// <exception cref="Pronesoft.Ecf.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rnc">RNC de la empresa (9 u 11 dígitos). En Sandbox usar valores con prefijo SBX.</param>
        /// <param name="file">Archivo del certificado en formato .p12 o .pfx.</param>
        /// <param name="password">Contraseña para desbloquear el certificado.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UploadCertificateResponse</returns>
        public async System.Threading.Tasks.Task<UploadCertificateResponse> UploadCertificateAsync(string rnc, FileParameter file, string password, System.Threading.CancellationToken cancellationToken = default)
        {
            Pronesoft.Ecf.Sdk.Client.ApiResponse<UploadCertificateResponse> localVarResponse = await UploadCertificateWithHttpInfoAsync(rnc, file, password, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Subir certificado digital (P12/PFX) Sube el certificado de firma digital emitido por DGII para una empresa. Se almacena cifrado con AES-256-CBC. No existe endpoint de descarga. Tip Sandbox: Los RNC con prefijo SBX no requieren certificado. 
        /// </summary>
        /// <exception cref="Pronesoft.Ecf.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rnc">RNC de la empresa (9 u 11 dígitos). En Sandbox usar valores con prefijo SBX.</param>
        /// <param name="file">Archivo del certificado en formato .p12 o .pfx.</param>
        /// <param name="password">Contraseña para desbloquear el certificado.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UploadCertificateResponse)</returns>
        public async System.Threading.Tasks.Task<Pronesoft.Ecf.Sdk.Client.ApiResponse<UploadCertificateResponse>> UploadCertificateWithHttpInfoAsync(string rnc, FileParameter file, string password, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'rnc' is set
            if (rnc == null)
                throw new Pronesoft.Ecf.Sdk.Client.ApiException(400, "Missing required parameter 'rnc' when calling DigitalCertificatesApi->UploadCertificate");

            // verify the required parameter 'file' is set
            if (file == null)
                throw new Pronesoft.Ecf.Sdk.Client.ApiException(400, "Missing required parameter 'file' when calling DigitalCertificatesApi->UploadCertificate");

            // verify the required parameter 'password' is set
            if (password == null)
                throw new Pronesoft.Ecf.Sdk.Client.ApiException(400, "Missing required parameter 'password' when calling DigitalCertificatesApi->UploadCertificate");


            Pronesoft.Ecf.Sdk.Client.RequestOptions localVarRequestOptions = new Pronesoft.Ecf.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Pronesoft.Ecf.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Pronesoft.Ecf.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("rnc", Pronesoft.Ecf.Sdk.Client.ClientUtils.ParameterToString(rnc)); // path parameter
            localVarRequestOptions.FileParameters.Add("file", file);
            localVarRequestOptions.FormParameters.Add("password", Pronesoft.Ecf.Sdk.Client.ClientUtils.ParameterToString(password)); // form parameter

            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<UploadCertificateResponse>("/{rnc}/certificates", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UploadCertificate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
