//
// AccountType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum AccountType: String, Codable, CaseIterable {
    case ct = "CT"
    case ah = "AH"
    case ot = "OT"
}
