//
// DocumentStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "PronesoftEcfAPI.DocumentStatus")
public typealias DocumentStatus = PronesoftEcfAPI.DocumentStatus

extension PronesoftEcfAPI {

public enum DocumentStatus: String, Codable, CaseIterable {
    case inProcess = "IN_PROCESS"
    case approved = "APPROVED"
    case conditionallyApproved = "CONDITIONALLY_APPROVED"
    case rejected = "REJECTED"
    case error = "ERROR"
    case errorComunication = "ERROR_COMUNICATION"
}
}
