//
// Transport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "PronesoftEcfAPI.Transport")
public typealias Transport = PronesoftEcfAPI.Transport

extension PronesoftEcfAPI {

/** Transport/delivery information (required for certain invoice types). */
public struct Transport: Codable, JSONEncodable, Hashable {

    /** Driver's full name. */
    public var driver: String?
    /** Vehicle identification number. */
    public var vehicleId: String?
    /** Vehicle license plate. */
    public var licensePlate: String?
    /** Delivery route description. */
    public var route: String?
    /** Departure date and time. */
    public var departureDate: Date?
    /** Estimated arrival date and time. */
    public var arrivalDate: Date?

    public init(driver: String? = nil, vehicleId: String? = nil, licensePlate: String? = nil, route: String? = nil, departureDate: Date? = nil, arrivalDate: Date? = nil) {
        self.driver = driver
        self.vehicleId = vehicleId
        self.licensePlate = licensePlate
        self.route = route
        self.departureDate = departureDate
        self.arrivalDate = arrivalDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case driver
        case vehicleId
        case licensePlate
        case route
        case departureDate
        case arrivalDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(driver, forKey: .driver)
        try container.encodeIfPresent(vehicleId, forKey: .vehicleId)
        try container.encodeIfPresent(licensePlate, forKey: .licensePlate)
        try container.encodeIfPresent(route, forKey: .route)
        try container.encodeIfPresent(departureDate, forKey: .departureDate)
        try container.encodeIfPresent(arrivalDate, forKey: .arrivalDate)
    }
}

}
