//
// WebhookConfigDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "PronesoftEcfAPI.WebhookConfigDetail")
public typealias WebhookConfigDetail = PronesoftEcfAPI.WebhookConfigDetail

extension PronesoftEcfAPI {

public struct WebhookConfigDetail: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var url: String?
    public var description: String?
    public var eventTypes: [WebhookEventType]?
    public var isActive: Bool?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var lastTriggeredAt: Date?
    public var deliveries: Int?

    public init(id: String? = nil, url: String? = nil, description: String? = nil, eventTypes: [WebhookEventType]? = nil, isActive: Bool? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, lastTriggeredAt: Date? = nil, deliveries: Int? = nil) {
        self.id = id
        self.url = url
        self.description = description
        self.eventTypes = eventTypes
        self.isActive = isActive
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.lastTriggeredAt = lastTriggeredAt
        self.deliveries = deliveries
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case url
        case description
        case eventTypes
        case isActive
        case createdAt
        case updatedAt
        case lastTriggeredAt
        case deliveries
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(eventTypes, forKey: .eventTypes)
        try container.encodeIfPresent(isActive, forKey: .isActive)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(lastTriggeredAt, forKey: .lastTriggeredAt)
        try container.encodeIfPresent(deliveries, forKey: .deliveries)
    }
}

}

@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PronesoftEcfAPI.WebhookConfigDetail: Identifiable {}
