<?php
/**
 * DocumentsReceivedApi
 * PHP version 8.1
 *
 * @category Class
 * @package  PronesoftEcf
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eCF-Pronesoft Integration API
 *
 * ## Descripción general API de nivel productivo para emitir Comprobantes Fiscales Electrónicos (e-CF) en la República Dominicana a través de la plataforma Pronesoft.  ## Autenticación — OAuth 2.0 Client Credentials  ### Pasos 1. Obtén tus credenciales desde el portal:    - Sandbox: https://ecf.sandbox.pronesoft.com → Apps → Default Sandbox App    - Producción: https://ecf.pronesoft.com → Integraciones → Apps → Crear App 2. Solicita un token via POST /oauth/token — válido por 24 horas (86400s). 3. Usa: Authorization: Bearer <accessToken> en cada request. 4. Renueva al recibir HTTP 401. Buena práctica: renovar 5 minutos antes del vencimiento.  ### Delegación multi-empresa Para actuar en nombre de una empresa asociada (sucursal), agrega:   x-tenant-id: <business-uuid> NO envíes x-tenant-id cuando actúes como la empresa principal.  ### Detalles del Sandbox - Usa cualquier RNC que comience con SBX (ej. SBX123456) — no se requiere certificado real. - Las secuencias son automáticas — no es necesario crearlas manualmente. - El campo environment en el cuerpo del documento DEBE ser TesteCF.  ### Scopes disponibles business:read, business:create, business:update, members:read, members:invite, members:revoke, certificates:read, certificates:upload, certificates:update, documents:read, documents:create, documents:send, documents:receive, documents:update, approvals:read, approvals:commercial, sequences:read, sequences:create, sequences:update, sequences:cancel, business_info:read, certification:read, certification:write, reports:read
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@pronesoft.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PronesoftEcf\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use PronesoftEcf\ApiException;
use PronesoftEcf\Configuration;
use PronesoftEcf\FormDataProcessor;
use PronesoftEcf\HeaderSelector;
use PronesoftEcf\ObjectSerializer;

/**
 * DocumentsReceivedApi Class Doc Comment
 *
 * @category Class
 * @package  PronesoftEcf
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DocumentsReceivedApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getReceivedDocumentById' => [
            'application/json',
        ],
        'getReceivedDocumentStatsBySupplier' => [
            'application/json',
        ],
        'getReceivedDocumentStatsSummary' => [
            'application/json',
        ],
        'listReceivedDocuments' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getReceivedDocumentById
     *
     * Obtener documento recibido por ID
     *
     * @param  string $id id (required)
     * @param  string|null $x_tenant_id UUID de la empresa asociada (sucursal). Incluir SOLO cuando se actúa en nombre de una sucursal. Omitir cuando se actúa como empresa principal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getReceivedDocumentById'] to see the possible values for this operation
     *
     * @throws \PronesoftEcf\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \PronesoftEcf\Model\ReceivedDocument|\PronesoftEcf\Model\ErrorResponse
     */
    public function getReceivedDocumentById($id, $x_tenant_id = null, string $contentType = self::contentTypes['getReceivedDocumentById'][0])
    {
        list($response) = $this->getReceivedDocumentByIdWithHttpInfo($id, $x_tenant_id, $contentType);
        return $response;
    }

    /**
     * Operation getReceivedDocumentByIdWithHttpInfo
     *
     * Obtener documento recibido por ID
     *
     * @param  string $id (required)
     * @param  string|null $x_tenant_id UUID de la empresa asociada (sucursal). Incluir SOLO cuando se actúa en nombre de una sucursal. Omitir cuando se actúa como empresa principal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getReceivedDocumentById'] to see the possible values for this operation
     *
     * @throws \PronesoftEcf\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \PronesoftEcf\Model\ReceivedDocument|\PronesoftEcf\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getReceivedDocumentByIdWithHttpInfo($id, $x_tenant_id = null, string $contentType = self::contentTypes['getReceivedDocumentById'][0])
    {
        $request = $this->getReceivedDocumentByIdRequest($id, $x_tenant_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PronesoftEcf\Model\ReceivedDocument',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\PronesoftEcf\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PronesoftEcf\Model\ReceivedDocument',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PronesoftEcf\Model\ReceivedDocument',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PronesoftEcf\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getReceivedDocumentByIdAsync
     *
     * Obtener documento recibido por ID
     *
     * @param  string $id (required)
     * @param  string|null $x_tenant_id UUID de la empresa asociada (sucursal). Incluir SOLO cuando se actúa en nombre de una sucursal. Omitir cuando se actúa como empresa principal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getReceivedDocumentById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReceivedDocumentByIdAsync($id, $x_tenant_id = null, string $contentType = self::contentTypes['getReceivedDocumentById'][0])
    {
        return $this->getReceivedDocumentByIdAsyncWithHttpInfo($id, $x_tenant_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getReceivedDocumentByIdAsyncWithHttpInfo
     *
     * Obtener documento recibido por ID
     *
     * @param  string $id (required)
     * @param  string|null $x_tenant_id UUID de la empresa asociada (sucursal). Incluir SOLO cuando se actúa en nombre de una sucursal. Omitir cuando se actúa como empresa principal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getReceivedDocumentById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReceivedDocumentByIdAsyncWithHttpInfo($id, $x_tenant_id = null, string $contentType = self::contentTypes['getReceivedDocumentById'][0])
    {
        $returnType = '\PronesoftEcf\Model\ReceivedDocument';
        $request = $this->getReceivedDocumentByIdRequest($id, $x_tenant_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getReceivedDocumentById'
     *
     * @param  string $id (required)
     * @param  string|null $x_tenant_id UUID de la empresa asociada (sucursal). Incluir SOLO cuando se actúa en nombre de una sucursal. Omitir cuando se actúa como empresa principal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getReceivedDocumentById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getReceivedDocumentByIdRequest($id, $x_tenant_id = null, string $contentType = self::contentTypes['getReceivedDocumentById'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getReceivedDocumentById'
            );
        }



        $resourcePath = '/documents/received/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_tenant_id !== null) {
            $headerParams['x-tenant-id'] = ObjectSerializer::toHeaderValue($x_tenant_id);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getReceivedDocumentStatsBySupplier
     *
     * Top 10 proveedores por volumen de documentos recibidos
     *
     * @param  string|null $x_tenant_id UUID de la empresa asociada (sucursal). Incluir SOLO cuando se actúa en nombre de una sucursal. Omitir cuando se actúa como empresa principal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getReceivedDocumentStatsBySupplier'] to see the possible values for this operation
     *
     * @throws \PronesoftEcf\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \PronesoftEcf\Model\GetReceivedDocumentStatsBySupplier200ResponseInner[]|\PronesoftEcf\Model\ErrorResponse
     */
    public function getReceivedDocumentStatsBySupplier($x_tenant_id = null, string $contentType = self::contentTypes['getReceivedDocumentStatsBySupplier'][0])
    {
        list($response) = $this->getReceivedDocumentStatsBySupplierWithHttpInfo($x_tenant_id, $contentType);
        return $response;
    }

    /**
     * Operation getReceivedDocumentStatsBySupplierWithHttpInfo
     *
     * Top 10 proveedores por volumen de documentos recibidos
     *
     * @param  string|null $x_tenant_id UUID de la empresa asociada (sucursal). Incluir SOLO cuando se actúa en nombre de una sucursal. Omitir cuando se actúa como empresa principal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getReceivedDocumentStatsBySupplier'] to see the possible values for this operation
     *
     * @throws \PronesoftEcf\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \PronesoftEcf\Model\GetReceivedDocumentStatsBySupplier200ResponseInner[]|\PronesoftEcf\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getReceivedDocumentStatsBySupplierWithHttpInfo($x_tenant_id = null, string $contentType = self::contentTypes['getReceivedDocumentStatsBySupplier'][0])
    {
        $request = $this->getReceivedDocumentStatsBySupplierRequest($x_tenant_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PronesoftEcf\Model\GetReceivedDocumentStatsBySupplier200ResponseInner[]',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\PronesoftEcf\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PronesoftEcf\Model\GetReceivedDocumentStatsBySupplier200ResponseInner[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PronesoftEcf\Model\GetReceivedDocumentStatsBySupplier200ResponseInner[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PronesoftEcf\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getReceivedDocumentStatsBySupplierAsync
     *
     * Top 10 proveedores por volumen de documentos recibidos
     *
     * @param  string|null $x_tenant_id UUID de la empresa asociada (sucursal). Incluir SOLO cuando se actúa en nombre de una sucursal. Omitir cuando se actúa como empresa principal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getReceivedDocumentStatsBySupplier'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReceivedDocumentStatsBySupplierAsync($x_tenant_id = null, string $contentType = self::contentTypes['getReceivedDocumentStatsBySupplier'][0])
    {
        return $this->getReceivedDocumentStatsBySupplierAsyncWithHttpInfo($x_tenant_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getReceivedDocumentStatsBySupplierAsyncWithHttpInfo
     *
     * Top 10 proveedores por volumen de documentos recibidos
     *
     * @param  string|null $x_tenant_id UUID de la empresa asociada (sucursal). Incluir SOLO cuando se actúa en nombre de una sucursal. Omitir cuando se actúa como empresa principal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getReceivedDocumentStatsBySupplier'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReceivedDocumentStatsBySupplierAsyncWithHttpInfo($x_tenant_id = null, string $contentType = self::contentTypes['getReceivedDocumentStatsBySupplier'][0])
    {
        $returnType = '\PronesoftEcf\Model\GetReceivedDocumentStatsBySupplier200ResponseInner[]';
        $request = $this->getReceivedDocumentStatsBySupplierRequest($x_tenant_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getReceivedDocumentStatsBySupplier'
     *
     * @param  string|null $x_tenant_id UUID de la empresa asociada (sucursal). Incluir SOLO cuando se actúa en nombre de una sucursal. Omitir cuando se actúa como empresa principal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getReceivedDocumentStatsBySupplier'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getReceivedDocumentStatsBySupplierRequest($x_tenant_id = null, string $contentType = self::contentTypes['getReceivedDocumentStatsBySupplier'][0])
    {



        $resourcePath = '/documents/received/stats/by-supplier';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_tenant_id !== null) {
            $headerParams['x-tenant-id'] = ObjectSerializer::toHeaderValue($x_tenant_id);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getReceivedDocumentStatsSummary
     *
     * Estadísticas de documentos recibidos
     *
     * @param  string|null $x_tenant_id UUID de la empresa asociada (sucursal). Incluir SOLO cuando se actúa en nombre de una sucursal. Omitir cuando se actúa como empresa principal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getReceivedDocumentStatsSummary'] to see the possible values for this operation
     *
     * @throws \PronesoftEcf\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \PronesoftEcf\Model\ReceivedDocumentStatsResponse|\PronesoftEcf\Model\ErrorResponse
     */
    public function getReceivedDocumentStatsSummary($x_tenant_id = null, string $contentType = self::contentTypes['getReceivedDocumentStatsSummary'][0])
    {
        list($response) = $this->getReceivedDocumentStatsSummaryWithHttpInfo($x_tenant_id, $contentType);
        return $response;
    }

    /**
     * Operation getReceivedDocumentStatsSummaryWithHttpInfo
     *
     * Estadísticas de documentos recibidos
     *
     * @param  string|null $x_tenant_id UUID de la empresa asociada (sucursal). Incluir SOLO cuando se actúa en nombre de una sucursal. Omitir cuando se actúa como empresa principal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getReceivedDocumentStatsSummary'] to see the possible values for this operation
     *
     * @throws \PronesoftEcf\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \PronesoftEcf\Model\ReceivedDocumentStatsResponse|\PronesoftEcf\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getReceivedDocumentStatsSummaryWithHttpInfo($x_tenant_id = null, string $contentType = self::contentTypes['getReceivedDocumentStatsSummary'][0])
    {
        $request = $this->getReceivedDocumentStatsSummaryRequest($x_tenant_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PronesoftEcf\Model\ReceivedDocumentStatsResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\PronesoftEcf\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PronesoftEcf\Model\ReceivedDocumentStatsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PronesoftEcf\Model\ReceivedDocumentStatsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PronesoftEcf\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getReceivedDocumentStatsSummaryAsync
     *
     * Estadísticas de documentos recibidos
     *
     * @param  string|null $x_tenant_id UUID de la empresa asociada (sucursal). Incluir SOLO cuando se actúa en nombre de una sucursal. Omitir cuando se actúa como empresa principal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getReceivedDocumentStatsSummary'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReceivedDocumentStatsSummaryAsync($x_tenant_id = null, string $contentType = self::contentTypes['getReceivedDocumentStatsSummary'][0])
    {
        return $this->getReceivedDocumentStatsSummaryAsyncWithHttpInfo($x_tenant_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getReceivedDocumentStatsSummaryAsyncWithHttpInfo
     *
     * Estadísticas de documentos recibidos
     *
     * @param  string|null $x_tenant_id UUID de la empresa asociada (sucursal). Incluir SOLO cuando se actúa en nombre de una sucursal. Omitir cuando se actúa como empresa principal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getReceivedDocumentStatsSummary'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReceivedDocumentStatsSummaryAsyncWithHttpInfo($x_tenant_id = null, string $contentType = self::contentTypes['getReceivedDocumentStatsSummary'][0])
    {
        $returnType = '\PronesoftEcf\Model\ReceivedDocumentStatsResponse';
        $request = $this->getReceivedDocumentStatsSummaryRequest($x_tenant_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getReceivedDocumentStatsSummary'
     *
     * @param  string|null $x_tenant_id UUID de la empresa asociada (sucursal). Incluir SOLO cuando se actúa en nombre de una sucursal. Omitir cuando se actúa como empresa principal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getReceivedDocumentStatsSummary'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getReceivedDocumentStatsSummaryRequest($x_tenant_id = null, string $contentType = self::contentTypes['getReceivedDocumentStatsSummary'][0])
    {



        $resourcePath = '/documents/received/stats/summary';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_tenant_id !== null) {
            $headerParams['x-tenant-id'] = ObjectSerializer::toHeaderValue($x_tenant_id);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listReceivedDocuments
     *
     * Listar documentos recibidos
     *
     * @param  string|null $x_tenant_id UUID de la empresa asociada (sucursal). Incluir SOLO cuando se actúa en nombre de una sucursal. Omitir cuando se actúa como empresa principal. (optional)
     * @param  string|null $ecf ecf (optional)
     * @param  string|null $type Tipo de documento (31, 32, 33, etc.) (optional)
     * @param  int|null $status status (optional)
     * @param  string|null $supplier_rnc RNC del emisor/proveedor (optional)
     * @param  float|null $amount_from amount_from (optional)
     * @param  float|null $amount_to amount_to (optional)
     * @param  bool|null $processed processed (optional)
     * @param  \DateTime|null $date_from date_from (optional)
     * @param  \DateTime|null $date_to date_to (optional)
     * @param  int|null $page page (optional, default to 1)
     * @param  int|null $limit limit (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listReceivedDocuments'] to see the possible values for this operation
     *
     * @throws \PronesoftEcf\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \PronesoftEcf\Model\ReceivedDocumentListResponse|\PronesoftEcf\Model\ErrorResponse
     */
    public function listReceivedDocuments($x_tenant_id = null, $ecf = null, $type = null, $status = null, $supplier_rnc = null, $amount_from = null, $amount_to = null, $processed = null, $date_from = null, $date_to = null, $page = 1, $limit = 10, string $contentType = self::contentTypes['listReceivedDocuments'][0])
    {
        list($response) = $this->listReceivedDocumentsWithHttpInfo($x_tenant_id, $ecf, $type, $status, $supplier_rnc, $amount_from, $amount_to, $processed, $date_from, $date_to, $page, $limit, $contentType);
        return $response;
    }

    /**
     * Operation listReceivedDocumentsWithHttpInfo
     *
     * Listar documentos recibidos
     *
     * @param  string|null $x_tenant_id UUID de la empresa asociada (sucursal). Incluir SOLO cuando se actúa en nombre de una sucursal. Omitir cuando se actúa como empresa principal. (optional)
     * @param  string|null $ecf (optional)
     * @param  string|null $type Tipo de documento (31, 32, 33, etc.) (optional)
     * @param  int|null $status (optional)
     * @param  string|null $supplier_rnc RNC del emisor/proveedor (optional)
     * @param  float|null $amount_from (optional)
     * @param  float|null $amount_to (optional)
     * @param  bool|null $processed (optional)
     * @param  \DateTime|null $date_from (optional)
     * @param  \DateTime|null $date_to (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listReceivedDocuments'] to see the possible values for this operation
     *
     * @throws \PronesoftEcf\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \PronesoftEcf\Model\ReceivedDocumentListResponse|\PronesoftEcf\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function listReceivedDocumentsWithHttpInfo($x_tenant_id = null, $ecf = null, $type = null, $status = null, $supplier_rnc = null, $amount_from = null, $amount_to = null, $processed = null, $date_from = null, $date_to = null, $page = 1, $limit = 10, string $contentType = self::contentTypes['listReceivedDocuments'][0])
    {
        $request = $this->listReceivedDocumentsRequest($x_tenant_id, $ecf, $type, $status, $supplier_rnc, $amount_from, $amount_to, $processed, $date_from, $date_to, $page, $limit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\PronesoftEcf\Model\ReceivedDocumentListResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\PronesoftEcf\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\PronesoftEcf\Model\ReceivedDocumentListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PronesoftEcf\Model\ReceivedDocumentListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\PronesoftEcf\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listReceivedDocumentsAsync
     *
     * Listar documentos recibidos
     *
     * @param  string|null $x_tenant_id UUID de la empresa asociada (sucursal). Incluir SOLO cuando se actúa en nombre de una sucursal. Omitir cuando se actúa como empresa principal. (optional)
     * @param  string|null $ecf (optional)
     * @param  string|null $type Tipo de documento (31, 32, 33, etc.) (optional)
     * @param  int|null $status (optional)
     * @param  string|null $supplier_rnc RNC del emisor/proveedor (optional)
     * @param  float|null $amount_from (optional)
     * @param  float|null $amount_to (optional)
     * @param  bool|null $processed (optional)
     * @param  \DateTime|null $date_from (optional)
     * @param  \DateTime|null $date_to (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listReceivedDocuments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listReceivedDocumentsAsync($x_tenant_id = null, $ecf = null, $type = null, $status = null, $supplier_rnc = null, $amount_from = null, $amount_to = null, $processed = null, $date_from = null, $date_to = null, $page = 1, $limit = 10, string $contentType = self::contentTypes['listReceivedDocuments'][0])
    {
        return $this->listReceivedDocumentsAsyncWithHttpInfo($x_tenant_id, $ecf, $type, $status, $supplier_rnc, $amount_from, $amount_to, $processed, $date_from, $date_to, $page, $limit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listReceivedDocumentsAsyncWithHttpInfo
     *
     * Listar documentos recibidos
     *
     * @param  string|null $x_tenant_id UUID de la empresa asociada (sucursal). Incluir SOLO cuando se actúa en nombre de una sucursal. Omitir cuando se actúa como empresa principal. (optional)
     * @param  string|null $ecf (optional)
     * @param  string|null $type Tipo de documento (31, 32, 33, etc.) (optional)
     * @param  int|null $status (optional)
     * @param  string|null $supplier_rnc RNC del emisor/proveedor (optional)
     * @param  float|null $amount_from (optional)
     * @param  float|null $amount_to (optional)
     * @param  bool|null $processed (optional)
     * @param  \DateTime|null $date_from (optional)
     * @param  \DateTime|null $date_to (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listReceivedDocuments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listReceivedDocumentsAsyncWithHttpInfo($x_tenant_id = null, $ecf = null, $type = null, $status = null, $supplier_rnc = null, $amount_from = null, $amount_to = null, $processed = null, $date_from = null, $date_to = null, $page = 1, $limit = 10, string $contentType = self::contentTypes['listReceivedDocuments'][0])
    {
        $returnType = '\PronesoftEcf\Model\ReceivedDocumentListResponse';
        $request = $this->listReceivedDocumentsRequest($x_tenant_id, $ecf, $type, $status, $supplier_rnc, $amount_from, $amount_to, $processed, $date_from, $date_to, $page, $limit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listReceivedDocuments'
     *
     * @param  string|null $x_tenant_id UUID de la empresa asociada (sucursal). Incluir SOLO cuando se actúa en nombre de una sucursal. Omitir cuando se actúa como empresa principal. (optional)
     * @param  string|null $ecf (optional)
     * @param  string|null $type Tipo de documento (31, 32, 33, etc.) (optional)
     * @param  int|null $status (optional)
     * @param  string|null $supplier_rnc RNC del emisor/proveedor (optional)
     * @param  float|null $amount_from (optional)
     * @param  float|null $amount_to (optional)
     * @param  bool|null $processed (optional)
     * @param  \DateTime|null $date_from (optional)
     * @param  \DateTime|null $date_to (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listReceivedDocuments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listReceivedDocumentsRequest($x_tenant_id = null, $ecf = null, $type = null, $status = null, $supplier_rnc = null, $amount_from = null, $amount_to = null, $processed = null, $date_from = null, $date_to = null, $page = 1, $limit = 10, string $contentType = self::contentTypes['listReceivedDocuments'][0])
    {












        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling DocumentsReceivedApi.listReceivedDocuments, must be smaller than or equal to 100.');
        }
        

        $resourcePath = '/documents/received';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $ecf,
            'ecf', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $type,
            'type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $status,
            'status', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $supplier_rnc,
            'supplierRnc', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $amount_from,
            'amountFrom', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $amount_to,
            'amountTo', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $processed,
            'processed', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date_from,
            'dateFrom', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date_to,
            'dateTo', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_tenant_id !== null) {
            $headerParams['x-tenant-id'] = ObjectSerializer::toHeaderValue($x_tenant_id);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
