/*
 * eCF-Pronesoft Master Integration API
 * Especificación de producción **200% detallada** de la API de eCF-Pronesoft. **Optimizada para la generación de SDKs de alta fidelidad.**  Esta especificación es el resultado de una auditoría exhaustiva del código fuente (NestJS), cubriendo el 100% de los DTOs, validaciones con regex, esquemas de Webhooks y  flujos de seguridad OAuth 2.0. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import Pronesoft.Ecf.JSON;

/**
 * GetNextNumber200ResponseData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-31T22:52:40.053005431-04:00[America/Santo_Domingo]", comments = "Generator version: 7.21.0")
public class GetNextNumber200ResponseData {
  public static final String SERIALIZED_NAME_NEXT_NUMBER = "nextNumber";
  @SerializedName(SERIALIZED_NAME_NEXT_NUMBER)
  @javax.annotation.Nullable
  private String nextNumber;

  public static final String SERIALIZED_NAME_REMAINING_NUMBERS = "remainingNumbers";
  @SerializedName(SERIALIZED_NAME_REMAINING_NUMBERS)
  @javax.annotation.Nullable
  private Integer remainingNumbers;

  public GetNextNumber200ResponseData() {
  }

  public GetNextNumber200ResponseData nextNumber(@javax.annotation.Nullable String nextNumber) {
    this.nextNumber = nextNumber;
    return this;
  }

  /**
   * Get nextNumber
   * @return nextNumber
   */
  @javax.annotation.Nullable
  public String getNextNumber() {
    return nextNumber;
  }

  public void setNextNumber(@javax.annotation.Nullable String nextNumber) {
    this.nextNumber = nextNumber;
  }


  public GetNextNumber200ResponseData remainingNumbers(@javax.annotation.Nullable Integer remainingNumbers) {
    this.remainingNumbers = remainingNumbers;
    return this;
  }

  /**
   * Get remainingNumbers
   * @return remainingNumbers
   */
  @javax.annotation.Nullable
  public Integer getRemainingNumbers() {
    return remainingNumbers;
  }

  public void setRemainingNumbers(@javax.annotation.Nullable Integer remainingNumbers) {
    this.remainingNumbers = remainingNumbers;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetNextNumber200ResponseData getNextNumber200ResponseData = (GetNextNumber200ResponseData) o;
    return Objects.equals(this.nextNumber, getNextNumber200ResponseData.nextNumber) &&
        Objects.equals(this.remainingNumbers, getNextNumber200ResponseData.remainingNumbers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nextNumber, remainingNumbers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetNextNumber200ResponseData {\n");
    sb.append("    nextNumber: ").append(toIndentedString(nextNumber)).append("\n");
    sb.append("    remainingNumbers: ").append(toIndentedString(remainingNumbers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("nextNumber", "remainingNumbers"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetNextNumber200ResponseData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetNextNumber200ResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in GetNextNumber200ResponseData is not found in the empty JSON string", GetNextNumber200ResponseData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetNextNumber200ResponseData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetNextNumber200ResponseData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("nextNumber") != null && !jsonObj.get("nextNumber").isJsonNull()) && !jsonObj.get("nextNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `nextNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nextNumber").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetNextNumber200ResponseData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetNextNumber200ResponseData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetNextNumber200ResponseData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetNextNumber200ResponseData.class));

       return (TypeAdapter<T>) new TypeAdapter<GetNextNumber200ResponseData>() {
           @Override
           public void write(JsonWriter out, GetNextNumber200ResponseData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetNextNumber200ResponseData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetNextNumber200ResponseData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetNextNumber200ResponseData
   * @throws IOException if the JSON string is invalid with respect to GetNextNumber200ResponseData
   */
  public static GetNextNumber200ResponseData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetNextNumber200ResponseData.class);
  }

  /**
   * Convert an instance of GetNextNumber200ResponseData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

