/*
 * eCF-Pronesoft Master Integration API
 *
 * Especificación de producción 100% exacta de la API de eCF-Pronesoft. **Diseñada para la generación automática de SDKs.**  Esta especificación ha sido auditada contra el código fuente real (DTOs, Controllers y Guards),  reflejando con total precisión la obligatoriedad de los campos y las estructuras de respuesta. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_access_token`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAccessTokenError {
    Status401(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


pub async fn get_access_token(configuration: &configuration::Configuration, o_auth_token_request: models::OAuthTokenRequest) -> Result<models::OAuthTokenResponse, Error<GetAccessTokenError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_o_auth_token_request = o_auth_token_request;

    let uri_str = format!("{}/oauth/token", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_o_auth_token_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OAuthTokenResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::OAuthTokenResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAccessTokenError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

