/*
 * eCF-Pronesoft Integration API
 * ## Descripción general API de nivel productivo para emitir Comprobantes Fiscales Electrónicos (e-CF) en la República Dominicana a través de la plataforma Pronesoft.  ## Autenticación — OAuth 2.0 Client Credentials  ### Pasos 1. Obtén tus credenciales desde el portal:    - Sandbox: https://ecf.sandbox.pronesoft.com → Apps → Default Sandbox App    - Producción: https://ecf.pronesoft.com → Integraciones → Apps → Crear App 2. Solicita un token via POST /oauth/token — válido por 24 horas (86400s). 3. Usa: Authorization: Bearer <accessToken> en cada request. 4. Renueva al recibir HTTP 401. Buena práctica: renovar 5 minutos antes del vencimiento.  ### Delegación multi-empresa Para actuar en nombre de una empresa asociada (sucursal), agrega:   x-tenant-id: <business-uuid> NO envíes x-tenant-id cuando actúes como la empresa principal.  ### Detalles del Sandbox - Usa cualquier RNC que comience con SBX (ej. SBX123456) — no se requiere certificado real. - Las secuencias son automáticas — no es necesario crearlas manualmente. - El campo environment en el cuerpo del documento DEBE ser TesteCF.  ### Scopes disponibles business:read, business:create, business:update, members:read, members:invite, members:revoke, certificates:read, certificates:upload, certificates:update, documents:read, documents:create, documents:send, documents:receive, documents:update, approvals:read, approvals:commercial, sequences:read, sequences:create, sequences:update, sequences:cancel, business_info:read, certification:read, certification:write, reports:read 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@pronesoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pronesoft.ecf.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.pronesoft.ecf.JSON;

/**
 * AdditionalTax
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-18T17:24:33.828594517-04:00[America/Santo_Domingo]", comments = "Generator version: 7.21.0")
public class AdditionalTax {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  @javax.annotation.Nonnull
  private String code;

  public static final String SERIALIZED_NAME_RATE = "rate";
  @SerializedName(SERIALIZED_NAME_RATE)
  @javax.annotation.Nonnull
  private BigDecimal rate;

  public static final String SERIALIZED_NAME_SPECIFIC_CONSUMPTION_TAX_AMOUNT = "specificConsumptionTaxAmount";
  @SerializedName(SERIALIZED_NAME_SPECIFIC_CONSUMPTION_TAX_AMOUNT)
  @javax.annotation.Nullable
  private BigDecimal specificConsumptionTaxAmount;

  public static final String SERIALIZED_NAME_AD_VALOREM_CONSUMPTION_TAX_AMOUNT = "adValoremConsumptionTaxAmount";
  @SerializedName(SERIALIZED_NAME_AD_VALOREM_CONSUMPTION_TAX_AMOUNT)
  @javax.annotation.Nullable
  private BigDecimal adValoremConsumptionTaxAmount;

  public static final String SERIALIZED_NAME_OTHER_ADDITIONAL_TAXES_AMOUNT = "otherAdditionalTaxesAmount";
  @SerializedName(SERIALIZED_NAME_OTHER_ADDITIONAL_TAXES_AMOUNT)
  @javax.annotation.Nullable
  private BigDecimal otherAdditionalTaxesAmount;

  public AdditionalTax() {
  }

  public AdditionalTax code(@javax.annotation.Nonnull String code) {
    this.code = code;
    return this;
  }

  /**
   * Get code
   * @return code
   */
  @javax.annotation.Nonnull
  public String getCode() {
    return code;
  }

  public void setCode(@javax.annotation.Nonnull String code) {
    this.code = code;
  }


  public AdditionalTax rate(@javax.annotation.Nonnull BigDecimal rate) {
    this.rate = rate;
    return this;
  }

  /**
   * Get rate
   * @return rate
   */
  @javax.annotation.Nonnull
  public BigDecimal getRate() {
    return rate;
  }

  public void setRate(@javax.annotation.Nonnull BigDecimal rate) {
    this.rate = rate;
  }


  public AdditionalTax specificConsumptionTaxAmount(@javax.annotation.Nullable BigDecimal specificConsumptionTaxAmount) {
    this.specificConsumptionTaxAmount = specificConsumptionTaxAmount;
    return this;
  }

  /**
   * Get specificConsumptionTaxAmount
   * @return specificConsumptionTaxAmount
   */
  @javax.annotation.Nullable
  public BigDecimal getSpecificConsumptionTaxAmount() {
    return specificConsumptionTaxAmount;
  }

  public void setSpecificConsumptionTaxAmount(@javax.annotation.Nullable BigDecimal specificConsumptionTaxAmount) {
    this.specificConsumptionTaxAmount = specificConsumptionTaxAmount;
  }


  public AdditionalTax adValoremConsumptionTaxAmount(@javax.annotation.Nullable BigDecimal adValoremConsumptionTaxAmount) {
    this.adValoremConsumptionTaxAmount = adValoremConsumptionTaxAmount;
    return this;
  }

  /**
   * Get adValoremConsumptionTaxAmount
   * @return adValoremConsumptionTaxAmount
   */
  @javax.annotation.Nullable
  public BigDecimal getAdValoremConsumptionTaxAmount() {
    return adValoremConsumptionTaxAmount;
  }

  public void setAdValoremConsumptionTaxAmount(@javax.annotation.Nullable BigDecimal adValoremConsumptionTaxAmount) {
    this.adValoremConsumptionTaxAmount = adValoremConsumptionTaxAmount;
  }


  public AdditionalTax otherAdditionalTaxesAmount(@javax.annotation.Nullable BigDecimal otherAdditionalTaxesAmount) {
    this.otherAdditionalTaxesAmount = otherAdditionalTaxesAmount;
    return this;
  }

  /**
   * Get otherAdditionalTaxesAmount
   * @return otherAdditionalTaxesAmount
   */
  @javax.annotation.Nullable
  public BigDecimal getOtherAdditionalTaxesAmount() {
    return otherAdditionalTaxesAmount;
  }

  public void setOtherAdditionalTaxesAmount(@javax.annotation.Nullable BigDecimal otherAdditionalTaxesAmount) {
    this.otherAdditionalTaxesAmount = otherAdditionalTaxesAmount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdditionalTax additionalTax = (AdditionalTax) o;
    return Objects.equals(this.code, additionalTax.code) &&
        Objects.equals(this.rate, additionalTax.rate) &&
        Objects.equals(this.specificConsumptionTaxAmount, additionalTax.specificConsumptionTaxAmount) &&
        Objects.equals(this.adValoremConsumptionTaxAmount, additionalTax.adValoremConsumptionTaxAmount) &&
        Objects.equals(this.otherAdditionalTaxesAmount, additionalTax.otherAdditionalTaxesAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, rate, specificConsumptionTaxAmount, adValoremConsumptionTaxAmount, otherAdditionalTaxesAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdditionalTax {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("    specificConsumptionTaxAmount: ").append(toIndentedString(specificConsumptionTaxAmount)).append("\n");
    sb.append("    adValoremConsumptionTaxAmount: ").append(toIndentedString(adValoremConsumptionTaxAmount)).append("\n");
    sb.append("    otherAdditionalTaxesAmount: ").append(toIndentedString(otherAdditionalTaxesAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("code", "rate", "specificConsumptionTaxAmount", "adValoremConsumptionTaxAmount", "otherAdditionalTaxesAmount"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("code", "rate"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AdditionalTax
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AdditionalTax.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AdditionalTax is not found in the empty JSON string", AdditionalTax.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AdditionalTax.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AdditionalTax` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AdditionalTax.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("code").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AdditionalTax.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AdditionalTax' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AdditionalTax> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AdditionalTax.class));

       return (TypeAdapter<T>) new TypeAdapter<AdditionalTax>() {
           @Override
           public void write(JsonWriter out, AdditionalTax value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AdditionalTax read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AdditionalTax given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AdditionalTax
   * @throws IOException if the JSON string is invalid with respect to AdditionalTax
   */
  public static AdditionalTax fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AdditionalTax.class);
  }

  /**
   * Convert an instance of AdditionalTax to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

