/*
 * eCF-Pronesoft Integration API
 * ## Overview Production-grade API for issuing Electronic Tax Receipts (e-CF) in the Dominican Republic through the Pronesoft platform.  ## Authentication — OAuth 2.0 Client Credentials  ### Steps 1. Get credentials from the portal:    - Sandbox: https://ecf.sandbox.pronesoft.com -> Apps -> Default Sandbox App    - Production: https://ecf.pronesoft.com -> Integrations -> Apps -> Create App 2. Request a token via POST /oauth/token — valid for 24 hours (86400s). 3. Use: Authorization: Bearer <accessToken> on every request. 4. Renew on HTTP 401. Best practice: renew 5 minutes before expiry.  ### Multi-company delegation To act on behalf of an associated company (branch), add:   x-tenant-id: <business-uuid> Do NOT send x-tenant-id when acting as the main company.  ### Sandbox specifics - Use any RNC starting with SBX (e.g. SBX123456) — no real certificate needed. - Sequences are automatic — no need to create them manually. - The environment field in the document body MUST be TesteCF.  ### Scopes business:read, business:create, business:update, members:read, members:invite, members:revoke, certificates:read, certificates:upload, certificates:update, documents:read, documents:create, documents:send, documents:receive, documents:update, approvals:read, approvals:commercial, sequences:read, sequences:create, sequences:update, sequences:cancel, business_info:read, certification:read, certification:write, reports:read 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@pronesoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pronesoft.ecf.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.pronesoft.ecf.JSON;

/**
 * ItemMiningInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-03T01:28:31.690460795-04:00[America/Santo_Domingo]", comments = "Generator version: 7.21.0")
public class ItemMiningInfo {
  public static final String SERIALIZED_NAME_NET_WEIGHT_KG = "netWeightKg";
  @SerializedName(SERIALIZED_NAME_NET_WEIGHT_KG)
  @javax.annotation.Nullable
  private BigDecimal netWeightKg;

  public static final String SERIALIZED_NAME_NET_WEIGHT_MINING = "netWeightMining";
  @SerializedName(SERIALIZED_NAME_NET_WEIGHT_MINING)
  @javax.annotation.Nullable
  private BigDecimal netWeightMining;

  public static final String SERIALIZED_NAME_AFFILIATION_TYPE = "affiliationType";
  @SerializedName(SERIALIZED_NAME_AFFILIATION_TYPE)
  @javax.annotation.Nullable
  private String affiliationType;

  public static final String SERIALIZED_NAME_SETTLEMENT = "settlement";
  @SerializedName(SERIALIZED_NAME_SETTLEMENT)
  @javax.annotation.Nullable
  private String settlement;

  public ItemMiningInfo() {
  }

  public ItemMiningInfo netWeightKg(@javax.annotation.Nullable BigDecimal netWeightKg) {
    this.netWeightKg = netWeightKg;
    return this;
  }

  /**
   * Get netWeightKg
   * @return netWeightKg
   */
  @javax.annotation.Nullable
  public BigDecimal getNetWeightKg() {
    return netWeightKg;
  }

  public void setNetWeightKg(@javax.annotation.Nullable BigDecimal netWeightKg) {
    this.netWeightKg = netWeightKg;
  }


  public ItemMiningInfo netWeightMining(@javax.annotation.Nullable BigDecimal netWeightMining) {
    this.netWeightMining = netWeightMining;
    return this;
  }

  /**
   * Get netWeightMining
   * @return netWeightMining
   */
  @javax.annotation.Nullable
  public BigDecimal getNetWeightMining() {
    return netWeightMining;
  }

  public void setNetWeightMining(@javax.annotation.Nullable BigDecimal netWeightMining) {
    this.netWeightMining = netWeightMining;
  }


  public ItemMiningInfo affiliationType(@javax.annotation.Nullable String affiliationType) {
    this.affiliationType = affiliationType;
    return this;
  }

  /**
   * Get affiliationType
   * @return affiliationType
   */
  @javax.annotation.Nullable
  public String getAffiliationType() {
    return affiliationType;
  }

  public void setAffiliationType(@javax.annotation.Nullable String affiliationType) {
    this.affiliationType = affiliationType;
  }


  public ItemMiningInfo settlement(@javax.annotation.Nullable String settlement) {
    this.settlement = settlement;
    return this;
  }

  /**
   * Get settlement
   * @return settlement
   */
  @javax.annotation.Nullable
  public String getSettlement() {
    return settlement;
  }

  public void setSettlement(@javax.annotation.Nullable String settlement) {
    this.settlement = settlement;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemMiningInfo itemMiningInfo = (ItemMiningInfo) o;
    return Objects.equals(this.netWeightKg, itemMiningInfo.netWeightKg) &&
        Objects.equals(this.netWeightMining, itemMiningInfo.netWeightMining) &&
        Objects.equals(this.affiliationType, itemMiningInfo.affiliationType) &&
        Objects.equals(this.settlement, itemMiningInfo.settlement);
  }

  @Override
  public int hashCode() {
    return Objects.hash(netWeightKg, netWeightMining, affiliationType, settlement);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemMiningInfo {\n");
    sb.append("    netWeightKg: ").append(toIndentedString(netWeightKg)).append("\n");
    sb.append("    netWeightMining: ").append(toIndentedString(netWeightMining)).append("\n");
    sb.append("    affiliationType: ").append(toIndentedString(affiliationType)).append("\n");
    sb.append("    settlement: ").append(toIndentedString(settlement)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("netWeightKg", "netWeightMining", "affiliationType", "settlement"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ItemMiningInfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ItemMiningInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ItemMiningInfo is not found in the empty JSON string", ItemMiningInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ItemMiningInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ItemMiningInfo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("affiliationType") != null && !jsonObj.get("affiliationType").isJsonNull()) && !jsonObj.get("affiliationType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `affiliationType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("affiliationType").toString()));
      }
      if ((jsonObj.get("settlement") != null && !jsonObj.get("settlement").isJsonNull()) && !jsonObj.get("settlement").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `settlement` to be a primitive type in the JSON string but got `%s`", jsonObj.get("settlement").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ItemMiningInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ItemMiningInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ItemMiningInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ItemMiningInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<ItemMiningInfo>() {
           @Override
           public void write(JsonWriter out, ItemMiningInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ItemMiningInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ItemMiningInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ItemMiningInfo
   * @throws IOException if the JSON string is invalid with respect to ItemMiningInfo
   */
  public static ItemMiningInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ItemMiningInfo.class);
  }

  /**
   * Convert an instance of ItemMiningInfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

