/* tslint:disable */
/* eslint-disable */
/**
 * eCF-Pronesoft Integration API
 * ## Overview Production-grade API for issuing Electronic Tax Receipts (e-CF) in the Dominican Republic through the Pronesoft platform.  ## Authentication — OAuth 2.0 Client Credentials  ### Steps 1. Get credentials from the portal:    - Sandbox: https://ecf.sandbox.pronesoft.com -> Apps -> Default Sandbox App    - Production: https://ecf.pronesoft.com -> Integrations -> Apps -> Create App 2. Request a token via POST /oauth/token — valid for 24 hours (86400s). 3. Use: Authorization: Bearer <accessToken> on every request. 4. Renew on HTTP 401. Best practice: renew 5 minutes before expiry.  ### Multi-company delegation To act on behalf of an associated company (branch), add:   x-tenant-id: <business-uuid> Do NOT send x-tenant-id when acting as the main company.  ### Sandbox specifics - Use any RNC starting with SBX (e.g. SBX123456) — no real certificate needed. - Sequences are automatic — no need to create them manually. - The environment field in the document body MUST be TesteCF.  ### Scopes business:read, business:create, business:update, members:read, members:invite, members:revoke, certificates:read, certificates:upload, certificates:update, documents:read, documents:create, documents:send, documents:receive, documents:update, approvals:read, approvals:commercial, sequences:read, sequences:create, sequences:update, sequences:cancel, business_info:read, certification:read, certification:write, reports:read 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@pronesoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ItemUnitPrice } from './ItemUnitPrice';
import {
    ItemUnitPriceFromJSON,
    ItemUnitPriceFromJSONTyped,
    ItemUnitPriceToJSON,
    ItemUnitPriceToJSONTyped,
} from './ItemUnitPrice';
import type { ItemDiscountInner } from './ItemDiscountInner';
import {
    ItemDiscountInnerFromJSON,
    ItemDiscountInnerFromJSONTyped,
    ItemDiscountInnerToJSON,
    ItemDiscountInnerToJSONTyped,
} from './ItemDiscountInner';
import type { BillingIndicator } from './BillingIndicator';
import {
    BillingIndicatorFromJSON,
    BillingIndicatorFromJSONTyped,
    BillingIndicatorToJSON,
    BillingIndicatorToJSONTyped,
} from './BillingIndicator';
import type { ItemQuantity } from './ItemQuantity';
import {
    ItemQuantityFromJSON,
    ItemQuantityFromJSONTyped,
    ItemQuantityToJSON,
    ItemQuantityToJSONTyped,
} from './ItemQuantity';
import type { ItemAdditionalTax } from './ItemAdditionalTax';
import {
    ItemAdditionalTaxFromJSON,
    ItemAdditionalTaxFromJSONTyped,
    ItemAdditionalTaxToJSON,
    ItemAdditionalTaxToJSONTyped,
} from './ItemAdditionalTax';
import type { ItemCodesInner } from './ItemCodesInner';
import {
    ItemCodesInnerFromJSON,
    ItemCodesInnerFromJSONTyped,
    ItemCodesInnerToJSON,
    ItemCodesInnerToJSONTyped,
} from './ItemCodesInner';
import type { ItemSurchargeInner } from './ItemSurchargeInner';
import {
    ItemSurchargeInnerFromJSON,
    ItemSurchargeInnerFromJSONTyped,
    ItemSurchargeInnerToJSON,
    ItemSurchargeInnerToJSONTyped,
} from './ItemSurchargeInner';
import type { Subquantity } from './Subquantity';
import {
    SubquantityFromJSON,
    SubquantityFromJSONTyped,
    SubquantityToJSON,
    SubquantityToJSONTyped,
} from './Subquantity';
import type { ItemAmount } from './ItemAmount';
import {
    ItemAmountFromJSON,
    ItemAmountFromJSONTyped,
    ItemAmountToJSON,
    ItemAmountToJSONTyped,
} from './ItemAmount';
import type { ItemAlternativeCurrency } from './ItemAlternativeCurrency';
import {
    ItemAlternativeCurrencyFromJSON,
    ItemAlternativeCurrencyFromJSONTyped,
    ItemAlternativeCurrencyToJSON,
    ItemAlternativeCurrencyToJSONTyped,
} from './ItemAlternativeCurrency';
import type { ItemMiningInfo } from './ItemMiningInfo';
import {
    ItemMiningInfoFromJSON,
    ItemMiningInfoFromJSONTyped,
    ItemMiningInfoToJSON,
    ItemMiningInfoToJSONTyped,
} from './ItemMiningInfo';
import type { ItemWithheldITBISAmount } from './ItemWithheldITBISAmount';
import {
    ItemWithheldITBISAmountFromJSON,
    ItemWithheldITBISAmountFromJSONTyped,
    ItemWithheldITBISAmountToJSON,
    ItemWithheldITBISAmountToJSONTyped,
} from './ItemWithheldITBISAmount';

/**
 * 
 * @export
 * @interface Item
 */
export interface Item {
    /**
     * 
     * @type {number}
     * @memberof Item
     */
    lineNumber?: number;
    /**
     * 
     * @type {Array<ItemCodesInner>}
     * @memberof Item
     */
    codes?: Array<ItemCodesInner>;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    description?: string;
    /**
     * 1=Good, 2=Service
     * @type {ItemTypeEnum}
     * @memberof Item
     */
    type: ItemTypeEnum;
    /**
     * 
     * @type {BillingIndicator}
     * @memberof Item
     */
    billingIndicator: BillingIndicator;
    /**
     * 
     * @type {number}
     * @memberof Item
     */
    withholdingAgentIndicator?: number;
    /**
     * 
     * @type {ItemWithheldITBISAmount}
     * @memberof Item
     */
    withheldITBISAmount?: ItemWithheldITBISAmount;
    /**
     * 
     * @type {ItemWithheldITBISAmount}
     * @memberof Item
     */
    withheldISRAmount?: ItemWithheldITBISAmount;
    /**
     * 
     * @type {ItemQuantity}
     * @memberof Item
     */
    quantity: ItemQuantity;
    /**
     * 
     * @type {number}
     * @memberof Item
     */
    unitOfMeasure?: number;
    /**
     * 
     * @type {ItemWithheldITBISAmount}
     * @memberof Item
     */
    referenceQuantity?: ItemWithheldITBISAmount;
    /**
     * 
     * @type {number}
     * @memberof Item
     */
    referenceUnit?: number;
    /**
     * 
     * @type {ItemWithheldITBISAmount}
     * @memberof Item
     */
    referenceUnitPrice?: ItemWithheldITBISAmount;
    /**
     * 
     * @type {Array<Subquantity>}
     * @memberof Item
     */
    subquantities?: Array<Subquantity>;
    /**
     * 
     * @type {number}
     * @memberof Item
     */
    alcoholDegree?: number;
    /**
     * 
     * @type {Date}
     * @memberof Item
     */
    manufacturingDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Item
     */
    expirationDate?: Date;
    /**
     * 
     * @type {ItemMiningInfo}
     * @memberof Item
     */
    miningInfo?: ItemMiningInfo;
    /**
     * 
     * @type {ItemUnitPrice}
     * @memberof Item
     */
    unitPrice: ItemUnitPrice;
    /**
     * 
     * @type {ItemWithheldITBISAmount}
     * @memberof Item
     */
    discountAmount?: ItemWithheldITBISAmount;
    /**
     * 
     * @type {Array<ItemDiscountInner>}
     * @memberof Item
     */
    discount?: Array<ItemDiscountInner>;
    /**
     * 
     * @type {ItemWithheldITBISAmount}
     * @memberof Item
     */
    surchargeAmount?: ItemWithheldITBISAmount;
    /**
     * 
     * @type {Array<ItemSurchargeInner>}
     * @memberof Item
     */
    surcharge?: Array<ItemSurchargeInner>;
    /**
     * 
     * @type {Array<ItemAdditionalTax>}
     * @memberof Item
     */
    additionalTaxes?: Array<ItemAdditionalTax>;
    /**
     * 
     * @type {ItemAlternativeCurrency}
     * @memberof Item
     */
    alternativeCurrency?: ItemAlternativeCurrency;
    /**
     * 
     * @type {ItemAmount}
     * @memberof Item
     */
    amount?: ItemAmount;
}


/**
 * @export
 */
export const ItemTypeEnum = {
    _1: '1',
    _2: '2'
} as const;
export type ItemTypeEnum = typeof ItemTypeEnum[keyof typeof ItemTypeEnum];


/**
 * Check if a given object implements the Item interface.
 */
export function instanceOfItem(value: object): value is Item {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('billingIndicator' in value) || value['billingIndicator'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('unitPrice' in value) || value['unitPrice'] === undefined) return false;
    return true;
}

export function ItemFromJSON(json: any): Item {
    return ItemFromJSONTyped(json, false);
}

export function ItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): Item {
    if (json == null) {
        return json;
    }
    return {
        
        'lineNumber': json['lineNumber'] == null ? undefined : json['lineNumber'],
        'codes': json['codes'] == null ? undefined : ((json['codes'] as Array<any>).map(ItemCodesInnerFromJSON)),
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'],
        'billingIndicator': BillingIndicatorFromJSON(json['billingIndicator']),
        'withholdingAgentIndicator': json['withholdingAgentIndicator'] == null ? undefined : json['withholdingAgentIndicator'],
        'withheldITBISAmount': json['withheldITBISAmount'] == null ? undefined : ItemWithheldITBISAmountFromJSON(json['withheldITBISAmount']),
        'withheldISRAmount': json['withheldISRAmount'] == null ? undefined : ItemWithheldITBISAmountFromJSON(json['withheldISRAmount']),
        'quantity': ItemQuantityFromJSON(json['quantity']),
        'unitOfMeasure': json['unitOfMeasure'] == null ? undefined : json['unitOfMeasure'],
        'referenceQuantity': json['referenceQuantity'] == null ? undefined : ItemWithheldITBISAmountFromJSON(json['referenceQuantity']),
        'referenceUnit': json['referenceUnit'] == null ? undefined : json['referenceUnit'],
        'referenceUnitPrice': json['referenceUnitPrice'] == null ? undefined : ItemWithheldITBISAmountFromJSON(json['referenceUnitPrice']),
        'subquantities': json['subquantities'] == null ? undefined : ((json['subquantities'] as Array<any>).map(SubquantityFromJSON)),
        'alcoholDegree': json['alcoholDegree'] == null ? undefined : json['alcoholDegree'],
        'manufacturingDate': json['manufacturingDate'] == null ? undefined : (new Date(json['manufacturingDate'])),
        'expirationDate': json['expirationDate'] == null ? undefined : (new Date(json['expirationDate'])),
        'miningInfo': json['miningInfo'] == null ? undefined : ItemMiningInfoFromJSON(json['miningInfo']),
        'unitPrice': ItemUnitPriceFromJSON(json['unitPrice']),
        'discountAmount': json['discountAmount'] == null ? undefined : ItemWithheldITBISAmountFromJSON(json['discountAmount']),
        'discount': json['discount'] == null ? undefined : ((json['discount'] as Array<any>).map(ItemDiscountInnerFromJSON)),
        'surchargeAmount': json['surchargeAmount'] == null ? undefined : ItemWithheldITBISAmountFromJSON(json['surchargeAmount']),
        'surcharge': json['surcharge'] == null ? undefined : ((json['surcharge'] as Array<any>).map(ItemSurchargeInnerFromJSON)),
        'additionalTaxes': json['additionalTaxes'] == null ? undefined : ((json['additionalTaxes'] as Array<any>).map(ItemAdditionalTaxFromJSON)),
        'alternativeCurrency': json['alternativeCurrency'] == null ? undefined : ItemAlternativeCurrencyFromJSON(json['alternativeCurrency']),
        'amount': json['amount'] == null ? undefined : ItemAmountFromJSON(json['amount']),
    };
}

export function ItemToJSON(json: any): Item {
    return ItemToJSONTyped(json, false);
}

export function ItemToJSONTyped(value?: Item | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lineNumber': value['lineNumber'],
        'codes': value['codes'] == null ? undefined : ((value['codes'] as Array<any>).map(ItemCodesInnerToJSON)),
        'name': value['name'],
        'description': value['description'],
        'type': value['type'],
        'billingIndicator': BillingIndicatorToJSON(value['billingIndicator']),
        'withholdingAgentIndicator': value['withholdingAgentIndicator'],
        'withheldITBISAmount': ItemWithheldITBISAmountToJSON(value['withheldITBISAmount']),
        'withheldISRAmount': ItemWithheldITBISAmountToJSON(value['withheldISRAmount']),
        'quantity': ItemQuantityToJSON(value['quantity']),
        'unitOfMeasure': value['unitOfMeasure'],
        'referenceQuantity': ItemWithheldITBISAmountToJSON(value['referenceQuantity']),
        'referenceUnit': value['referenceUnit'],
        'referenceUnitPrice': ItemWithheldITBISAmountToJSON(value['referenceUnitPrice']),
        'subquantities': value['subquantities'] == null ? undefined : ((value['subquantities'] as Array<any>).map(SubquantityToJSON)),
        'alcoholDegree': value['alcoholDegree'],
        'manufacturingDate': value['manufacturingDate'] == null ? value['manufacturingDate'] : value['manufacturingDate'].toISOString(),
        'expirationDate': value['expirationDate'] == null ? value['expirationDate'] : value['expirationDate'].toISOString(),
        'miningInfo': ItemMiningInfoToJSON(value['miningInfo']),
        'unitPrice': ItemUnitPriceToJSON(value['unitPrice']),
        'discountAmount': ItemWithheldITBISAmountToJSON(value['discountAmount']),
        'discount': value['discount'] == null ? undefined : ((value['discount'] as Array<any>).map(ItemDiscountInnerToJSON)),
        'surchargeAmount': ItemWithheldITBISAmountToJSON(value['surchargeAmount']),
        'surcharge': value['surcharge'] == null ? undefined : ((value['surcharge'] as Array<any>).map(ItemSurchargeInnerToJSON)),
        'additionalTaxes': value['additionalTaxes'] == null ? undefined : ((value['additionalTaxes'] as Array<any>).map(ItemAdditionalTaxToJSON)),
        'alternativeCurrency': ItemAlternativeCurrencyToJSON(value['alternativeCurrency']),
        'amount': ItemAmountToJSON(value['amount']),
    };
}

