=begin
#eCF-Pronesoft Integration API

### Descripción general API de nivel productivo para emitir Comprobantes Fiscales Electrónicos (e-CF) en la República Dominicana a través de la plataforma Pronesoft.  ## Autenticación — OAuth 2.0 Client Credentials  ### Pasos 1. Obtén tus credenciales desde el portal:    - Sandbox: https://ecf.sandbox.pronesoft.com → Apps → Default Sandbox App    - Producción: https://ecf.pronesoft.com → Integraciones → Apps → Crear App 2. Solicita un token via POST /oauth/token — válido por 24 horas (86400s). 3. Usa: Authorization: Bearer <accessToken> en cada request. 4. Renueva al recibir HTTP 401. Buena práctica: renovar 5 minutos antes del vencimiento.  ### Delegación multi-empresa Para actuar en nombre de una empresa asociada (sucursal), agrega:   x-tenant-id: <business-uuid> NO envíes x-tenant-id cuando actúes como la empresa principal.  ### Detalles del Sandbox - Usa cualquier RNC que comience con SBX (ej. SBX123456) — no se requiere certificado real. - Las secuencias son automáticas — no es necesario crearlas manualmente. - El campo environment en el cuerpo del documento DEBE ser TesteCF.  ### Scopes disponibles business:read, business:create, business:update, members:read, members:invite, members:revoke, certificates:read, certificates:upload, certificates:update, documents:read, documents:create, documents:send, documents:receive, documents:update, approvals:read, approvals:commercial, sequences:read, sequences:create, sequences:update, sequences:cancel, business_info:read, certification:read, certification:write, reports:read 

The version of the OpenAPI document: 1.2.0
Contact: support@pronesoft.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module PronesoftEcf
  # Payload del evento `commercial.approval`. Se dispara cuando una aprobación comercial es actualizada.
  class CommercialApprovalPayload < ApiModelBase
    attr_accessor :encf

    attr_accessor :sender_rnc

    attr_accessor :receiver_rnc

    attr_accessor :total_amount

    attr_accessor :issue_date

    attr_accessor :approval_status

    attr_accessor :approval_date

    # Código de rechazo (solo si approvalStatus es 'rejected').
    attr_accessor :rejection_code

    # Descripción del rechazo (solo si approvalStatus es 'rejected').
    attr_accessor :rejection_description

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'encf' => :'encf',
        :'sender_rnc' => :'senderRnc',
        :'receiver_rnc' => :'receiverRnc',
        :'total_amount' => :'totalAmount',
        :'issue_date' => :'issueDate',
        :'approval_status' => :'approvalStatus',
        :'approval_date' => :'approvalDate',
        :'rejection_code' => :'rejectionCode',
        :'rejection_description' => :'rejectionDescription'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'encf' => :'String',
        :'sender_rnc' => :'String',
        :'receiver_rnc' => :'String',
        :'total_amount' => :'Float',
        :'issue_date' => :'Time',
        :'approval_status' => :'String',
        :'approval_date' => :'Time',
        :'rejection_code' => :'String',
        :'rejection_description' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'rejection_code',
        :'rejection_description'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PronesoftEcf::CommercialApprovalPayload` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PronesoftEcf::CommercialApprovalPayload`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'encf')
        self.encf = attributes[:'encf']
      else
        self.encf = nil
      end

      if attributes.key?(:'sender_rnc')
        self.sender_rnc = attributes[:'sender_rnc']
      else
        self.sender_rnc = nil
      end

      if attributes.key?(:'receiver_rnc')
        self.receiver_rnc = attributes[:'receiver_rnc']
      else
        self.receiver_rnc = nil
      end

      if attributes.key?(:'total_amount')
        self.total_amount = attributes[:'total_amount']
      else
        self.total_amount = nil
      end

      if attributes.key?(:'issue_date')
        self.issue_date = attributes[:'issue_date']
      else
        self.issue_date = nil
      end

      if attributes.key?(:'approval_status')
        self.approval_status = attributes[:'approval_status']
      else
        self.approval_status = nil
      end

      if attributes.key?(:'approval_date')
        self.approval_date = attributes[:'approval_date']
      else
        self.approval_date = nil
      end

      if attributes.key?(:'rejection_code')
        self.rejection_code = attributes[:'rejection_code']
      end

      if attributes.key?(:'rejection_description')
        self.rejection_description = attributes[:'rejection_description']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @encf.nil?
        invalid_properties.push('invalid value for "encf", encf cannot be nil.')
      end

      if @sender_rnc.nil?
        invalid_properties.push('invalid value for "sender_rnc", sender_rnc cannot be nil.')
      end

      if @receiver_rnc.nil?
        invalid_properties.push('invalid value for "receiver_rnc", receiver_rnc cannot be nil.')
      end

      if @total_amount.nil?
        invalid_properties.push('invalid value for "total_amount", total_amount cannot be nil.')
      end

      if @issue_date.nil?
        invalid_properties.push('invalid value for "issue_date", issue_date cannot be nil.')
      end

      if @approval_status.nil?
        invalid_properties.push('invalid value for "approval_status", approval_status cannot be nil.')
      end

      if @approval_date.nil?
        invalid_properties.push('invalid value for "approval_date", approval_date cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @encf.nil?
      return false if @sender_rnc.nil?
      return false if @receiver_rnc.nil?
      return false if @total_amount.nil?
      return false if @issue_date.nil?
      return false if @approval_status.nil?
      approval_status_validator = EnumAttributeValidator.new('String', ["approved", "rejected"])
      return false unless approval_status_validator.valid?(@approval_status)
      return false if @approval_date.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] encf Value to be assigned
    def encf=(encf)
      if encf.nil?
        fail ArgumentError, 'encf cannot be nil'
      end

      @encf = encf
    end

    # Custom attribute writer method with validation
    # @param [Object] sender_rnc Value to be assigned
    def sender_rnc=(sender_rnc)
      if sender_rnc.nil?
        fail ArgumentError, 'sender_rnc cannot be nil'
      end

      @sender_rnc = sender_rnc
    end

    # Custom attribute writer method with validation
    # @param [Object] receiver_rnc Value to be assigned
    def receiver_rnc=(receiver_rnc)
      if receiver_rnc.nil?
        fail ArgumentError, 'receiver_rnc cannot be nil'
      end

      @receiver_rnc = receiver_rnc
    end

    # Custom attribute writer method with validation
    # @param [Object] total_amount Value to be assigned
    def total_amount=(total_amount)
      if total_amount.nil?
        fail ArgumentError, 'total_amount cannot be nil'
      end

      @total_amount = total_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] issue_date Value to be assigned
    def issue_date=(issue_date)
      if issue_date.nil?
        fail ArgumentError, 'issue_date cannot be nil'
      end

      @issue_date = issue_date
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] approval_status Object to be assigned
    def approval_status=(approval_status)
      validator = EnumAttributeValidator.new('String', ["approved", "rejected"])
      unless validator.valid?(approval_status)
        fail ArgumentError, "invalid value for \"approval_status\", must be one of #{validator.allowable_values}."
      end
      @approval_status = approval_status
    end

    # Custom attribute writer method with validation
    # @param [Object] approval_date Value to be assigned
    def approval_date=(approval_date)
      if approval_date.nil?
        fail ArgumentError, 'approval_date cannot be nil'
      end

      @approval_date = approval_date
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          encf == o.encf &&
          sender_rnc == o.sender_rnc &&
          receiver_rnc == o.receiver_rnc &&
          total_amount == o.total_amount &&
          issue_date == o.issue_date &&
          approval_status == o.approval_status &&
          approval_date == o.approval_date &&
          rejection_code == o.rejection_code &&
          rejection_description == o.rejection_description
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [encf, sender_rnc, receiver_rnc, total_amount, issue_date, approval_status, approval_date, rejection_code, rejection_description].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
