/*
 * eCF-Pronesoft Master Integration API
 *
 * Especificación de producción **200% detallada** de la API de eCF-Pronesoft. **Optimizada para la generación de SDKs de alta fidelidad.**  Esta especificación es el resultado de una auditoría exhaustiva del código fuente (NestJS), cubriendo el 100% de los DTOs, validaciones con regex, esquemas de Webhooks y  flujos de seguridad OAuth 2.0. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DocumentReceivedPayload {
    #[serde(rename = "encf", skip_serializing_if = "Option::is_none")]
    pub encf: Option<String>,
    #[serde(rename = "senderRnc", skip_serializing_if = "Option::is_none")]
    pub sender_rnc: Option<String>,
    #[serde(rename = "totalAmount", skip_serializing_if = "Option::is_none")]
    pub total_amount: Option<f64>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
}

impl DocumentReceivedPayload {
    pub fn new() -> DocumentReceivedPayload {
        DocumentReceivedPayload {
            encf: None,
            sender_rnc: None,
            total_amount: None,
            status: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "received")]
    Received,
    #[serde(rename = "rejected")]
    Rejected,
}

impl Default for Status {
    fn default() -> Status {
        Self::Received
    }
}

