/* tslint:disable */
/* eslint-disable */
/**
 * eCF-Pronesoft Integration API
 * ## Descripción general API de nivel productivo para emitir Comprobantes Fiscales Electrónicos (e-CF) en la República Dominicana a través de la plataforma Pronesoft.  ## Autenticación — OAuth 2.0 Client Credentials  ### Pasos 1. Obtén tus credenciales desde el portal:    - Sandbox: https://ecf.sandbox.pronesoft.com → Apps → Default Sandbox App    - Producción: https://ecf.pronesoft.com → Integraciones → Apps → Crear App 2. Solicita un token via POST /oauth/token — válido por 24 horas (86400s). 3. Usa: Authorization: Bearer <accessToken> en cada request. 4. Renueva al recibir HTTP 401. Buena práctica: renovar 5 minutos antes del vencimiento.  ### Delegación multi-empresa Para actuar en nombre de una empresa asociada (sucursal), agrega:   x-tenant-id: <business-uuid> NO envíes x-tenant-id cuando actúes como la empresa principal.  ### Detalles del Sandbox - Usa cualquier RNC que comience con SBX (ej. SBX123456) — no se requiere certificado real. - Las secuencias son automáticas — no es necesario crearlas manualmente. - El campo environment en el cuerpo del documento DEBE ser TesteCF.  ### Scopes disponibles business:read, business:create, business:update, members:read, members:invite, members:revoke, certificates:read, certificates:upload, certificates:update, documents:read, documents:create, documents:send, documents:receive, documents:update, approvals:read, approvals:commercial, sequences:read, sequences:create, sequences:update, sequences:cancel, business_info:read, certification:read, certification:write, reports:read 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@pronesoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Payload del evento `sequence.voided`. Se anuló un rango de secuencias.
 * @export
 * @interface SequenceVoidedPayload
 */
export interface SequenceVoidedPayload {
    /**
     * 
     * @type {string}
     * @memberof SequenceVoidedPayload
     */
    sequenceType: string;
    /**
     * Rango de NCF anulados.
     * @type {string}
     * @memberof SequenceVoidedPayload
     */
    voidedRange: string;
    /**
     * Motivo de la anulación.
     * @type {string}
     * @memberof SequenceVoidedPayload
     */
    reason: string;
}

/**
 * Check if a given object implements the SequenceVoidedPayload interface.
 */
export function instanceOfSequenceVoidedPayload(value: object): value is SequenceVoidedPayload {
    if (!('sequenceType' in value) || value['sequenceType'] === undefined) return false;
    if (!('voidedRange' in value) || value['voidedRange'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function SequenceVoidedPayloadFromJSON(json: any): SequenceVoidedPayload {
    return SequenceVoidedPayloadFromJSONTyped(json, false);
}

export function SequenceVoidedPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): SequenceVoidedPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'sequenceType': json['sequenceType'],
        'voidedRange': json['voidedRange'],
        'reason': json['reason'],
    };
}

export function SequenceVoidedPayloadToJSON(json: any): SequenceVoidedPayload {
    return SequenceVoidedPayloadToJSONTyped(json, false);
}

export function SequenceVoidedPayloadToJSONTyped(value?: SequenceVoidedPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sequenceType': value['sequenceType'],
        'voidedRange': value['voidedRange'],
        'reason': value['reason'],
    };
}

