// <auto-generated>
/*
 * eCF-Pronesoft Integration API
 *
 * ## Descripción general API de nivel productivo para emitir Comprobantes Fiscales Electrónicos (e-CF) en la República Dominicana a través de la plataforma Pronesoft.  ## Autenticación — OAuth 2.0 Client Credentials  ### Pasos 1. Obtén tus credenciales desde el portal:    - Sandbox: https://ecf.sandbox.pronesoft.com → Apps → Default Sandbox App    - Producción: https://ecf.pronesoft.com → Integraciones → Apps → Crear App 2. Solicita un token via POST /oauth/token — válido por 24 horas (86400s). 3. Usa: Authorization: Bearer <accessToken> en cada request. 4. Renueva al recibir HTTP 401. Buena práctica: renovar 5 minutos antes del vencimiento.  ### Delegación multi-empresa Para actuar en nombre de una empresa asociada (sucursal), agrega:   x-tenant-id: <business-uuid> NO envíes x-tenant-id cuando actúes como la empresa principal.  ### Detalles del Sandbox - Usa cualquier RNC que comience con SBX (ej. SBX123456) — no se requiere certificado real. - Las secuencias son automáticas — no es necesario crearlas manualmente. - El campo environment en el cuerpo del documento DEBE ser TesteCF.  ### Scopes disponibles business:read, business:create, business:update, members:read, members:invite, members:revoke, certificates:read, certificates:upload, certificates:update, documents:read, documents:create, documents:send, documents:receive, documents:update, approvals:read, approvals:commercial, sequences:read, sequences:create, sequences:update, sequences:cancel, business_info:read, certification:read, certification:write, reports:read 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@pronesoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pronesoft.Ecf.Sdk.Client;

namespace Pronesoft.Ecf.Sdk.Model
{
    /// <summary>
    /// AdditionalTax
    /// </summary>
    public partial class AdditionalTax : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AdditionalTax" /> class.
        /// </summary>
        /// <param name="code">code</param>
        /// <param name="rate">rate</param>
        /// <param name="specificConsumptionTaxAmount">specificConsumptionTaxAmount</param>
        /// <param name="adValoremConsumptionTaxAmount">adValoremConsumptionTaxAmount</param>
        /// <param name="otherAdditionalTaxesAmount">otherAdditionalTaxesAmount</param>
        [JsonConstructor]
        public AdditionalTax(string code, decimal rate, Option<decimal?> specificConsumptionTaxAmount = default, Option<decimal?> adValoremConsumptionTaxAmount = default, Option<decimal?> otherAdditionalTaxesAmount = default)
        {
            Code = code;
            Rate = rate;
            SpecificConsumptionTaxAmountOption = specificConsumptionTaxAmount;
            AdValoremConsumptionTaxAmountOption = adValoremConsumptionTaxAmount;
            OtherAdditionalTaxesAmountOption = otherAdditionalTaxesAmount;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [JsonPropertyName("code")]
        public string Code { get; set; }

        /// <summary>
        /// Gets or Sets Rate
        /// </summary>
        [JsonPropertyName("rate")]
        public decimal Rate { get; set; }

        /// <summary>
        /// Used to track the state of SpecificConsumptionTaxAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> SpecificConsumptionTaxAmountOption { get; private set; }

        /// <summary>
        /// Gets or Sets SpecificConsumptionTaxAmount
        /// </summary>
        [JsonPropertyName("specificConsumptionTaxAmount")]
        public decimal? SpecificConsumptionTaxAmount { get { return this.SpecificConsumptionTaxAmountOption; } set { this.SpecificConsumptionTaxAmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of AdValoremConsumptionTaxAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> AdValoremConsumptionTaxAmountOption { get; private set; }

        /// <summary>
        /// Gets or Sets AdValoremConsumptionTaxAmount
        /// </summary>
        [JsonPropertyName("adValoremConsumptionTaxAmount")]
        public decimal? AdValoremConsumptionTaxAmount { get { return this.AdValoremConsumptionTaxAmountOption; } set { this.AdValoremConsumptionTaxAmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of OtherAdditionalTaxesAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> OtherAdditionalTaxesAmountOption { get; private set; }

        /// <summary>
        /// Gets or Sets OtherAdditionalTaxesAmount
        /// </summary>
        [JsonPropertyName("otherAdditionalTaxesAmount")]
        public decimal? OtherAdditionalTaxesAmount { get { return this.OtherAdditionalTaxesAmountOption; } set { this.OtherAdditionalTaxesAmountOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AdditionalTax {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Rate: ").Append(Rate).Append("\n");
            sb.Append("  SpecificConsumptionTaxAmount: ").Append(SpecificConsumptionTaxAmount).Append("\n");
            sb.Append("  AdValoremConsumptionTaxAmount: ").Append(AdValoremConsumptionTaxAmount).Append("\n");
            sb.Append("  OtherAdditionalTaxesAmount: ").Append(OtherAdditionalTaxesAmount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Code (string) maxLength
            if (this.Code != null && this.Code.Length > 3)
            {
                yield return new ValidationResult("Invalid value for Code, length must be less than 3.", new [] { "Code" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AdditionalTax" />
    /// </summary>
    public class AdditionalTaxJsonConverter : JsonConverter<AdditionalTax>
    {
        /// <summary>
        /// Deserializes json to <see cref="AdditionalTax" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AdditionalTax Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> code = default;
            Option<decimal?> rate = default;
            Option<decimal?> specificConsumptionTaxAmount = default;
            Option<decimal?> adValoremConsumptionTaxAmount = default;
            Option<decimal?> otherAdditionalTaxesAmount = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "code":
                            code = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "rate":
                            rate = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "specificConsumptionTaxAmount":
                            specificConsumptionTaxAmount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "adValoremConsumptionTaxAmount":
                            adValoremConsumptionTaxAmount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "otherAdditionalTaxesAmount":
                            otherAdditionalTaxesAmount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!code.IsSet)
                throw new ArgumentException("Property is required for class AdditionalTax.", nameof(code));

            if (!rate.IsSet)
                throw new ArgumentException("Property is required for class AdditionalTax.", nameof(rate));

            if (code.IsSet && code.Value == null)
                throw new ArgumentNullException(nameof(code), "Property is not nullable for class AdditionalTax.");

            if (rate.IsSet && rate.Value == null)
                throw new ArgumentNullException(nameof(rate), "Property is not nullable for class AdditionalTax.");

            if (specificConsumptionTaxAmount.IsSet && specificConsumptionTaxAmount.Value == null)
                throw new ArgumentNullException(nameof(specificConsumptionTaxAmount), "Property is not nullable for class AdditionalTax.");

            if (adValoremConsumptionTaxAmount.IsSet && adValoremConsumptionTaxAmount.Value == null)
                throw new ArgumentNullException(nameof(adValoremConsumptionTaxAmount), "Property is not nullable for class AdditionalTax.");

            if (otherAdditionalTaxesAmount.IsSet && otherAdditionalTaxesAmount.Value == null)
                throw new ArgumentNullException(nameof(otherAdditionalTaxesAmount), "Property is not nullable for class AdditionalTax.");

            return new AdditionalTax(code.Value!, rate.Value!.Value!, specificConsumptionTaxAmount, adValoremConsumptionTaxAmount, otherAdditionalTaxesAmount);
        }

        /// <summary>
        /// Serializes a <see cref="AdditionalTax" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="additionalTax"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AdditionalTax additionalTax, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, additionalTax, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AdditionalTax" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="additionalTax"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AdditionalTax additionalTax, JsonSerializerOptions jsonSerializerOptions)
        {
            if (additionalTax.Code == null)
                throw new ArgumentNullException(nameof(additionalTax.Code), "Property is required for class AdditionalTax.");

            writer.WriteString("code", additionalTax.Code);

            writer.WriteNumber("rate", additionalTax.Rate);

            if (additionalTax.SpecificConsumptionTaxAmountOption.IsSet)
                writer.WriteNumber("specificConsumptionTaxAmount", additionalTax.SpecificConsumptionTaxAmountOption.Value!.Value);

            if (additionalTax.AdValoremConsumptionTaxAmountOption.IsSet)
                writer.WriteNumber("adValoremConsumptionTaxAmount", additionalTax.AdValoremConsumptionTaxAmountOption.Value!.Value);

            if (additionalTax.OtherAdditionalTaxesAmountOption.IsSet)
                writer.WriteNumber("otherAdditionalTaxesAmount", additionalTax.OtherAdditionalTaxesAmountOption.Value!.Value);
        }
    }
}
