// <auto-generated>
/*
 * eCF-Pronesoft Master Integration API
 *
 * **Highly detailed** production-grade API specification for eCF-Pronesoft. **Optimized for high-fidelity SDK generation.**  This specification is the result of an exhaustive audit of the source code (NestJS), covering 100% of the DTOs, regex validations, Webhook schemas, and  OAuth 2.0 security flows. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contacto@pronesoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pronesoft.Ecf.Sdk.Client;

namespace Pronesoft.Ecf.Sdk.Model
{
    /// <summary>
    /// Item
    /// </summary>
    public partial class Item : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Item" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="type">type</param>
        /// <param name="billingIndicator">billingIndicator</param>
        /// <param name="quantity">quantity</param>
        /// <param name="unitPrice">unitPrice</param>
        /// <param name="amount">amount</param>
        /// <param name="lineNumber">lineNumber</param>
        /// <param name="discountAmount">discountAmount</param>
        /// <param name="additionalTaxes">additionalTaxes</param>
        /// <param name="subquantities">subquantities</param>
        /// <param name="alcoholDegree">alcoholDegree</param>
        [JsonConstructor]
        public Item(string name, TypeEnum type, BillingIndicator billingIndicator, string quantity, string unitPrice, decimal amount, Option<int?> lineNumber = default, Option<decimal?> discountAmount = default, Option<List<ItemAdditionalTax>?> additionalTaxes = default, Option<List<Subquantity>?> subquantities = default, Option<decimal?> alcoholDegree = default)
        {
            Name = name;
            Type = type;
            BillingIndicator = billingIndicator;
            Quantity = quantity;
            UnitPrice = unitPrice;
            Amount = amount;
            LineNumberOption = lineNumber;
            DiscountAmountOption = discountAmount;
            AdditionalTaxesOption = additionalTaxes;
            SubquantitiesOption = subquantities;
            AlcoholDegreeOption = alcoholDegree;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Type
        /// </summary>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum _1 for value: 1
            /// </summary>
            _1 = 1,

            /// <summary>
            /// Enum _2 for value: 2
            /// </summary>
            _2 = 2
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("1"))
                return TypeEnum._1;

            if (value.Equals("2"))
                return TypeEnum._2;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("1"))
                return TypeEnum._1;

            if (value.Equals("2"))
                return TypeEnum._2;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum value)
        {
            if (value == TypeEnum._1)
                return "1";

            if (value == TypeEnum._2)
                return "2";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Gets or Sets BillingIndicator
        /// </summary>
        [JsonPropertyName("billingIndicator")]
        public BillingIndicator BillingIndicator { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [JsonPropertyName("quantity")]
        public string Quantity { get; set; }

        /// <summary>
        /// Gets or Sets UnitPrice
        /// </summary>
        [JsonPropertyName("unitPrice")]
        public string UnitPrice { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [JsonPropertyName("amount")]
        public decimal Amount { get; set; }

        /// <summary>
        /// Used to track the state of LineNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> LineNumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets LineNumber
        /// </summary>
        [JsonPropertyName("lineNumber")]
        public int? LineNumber { get { return this.LineNumberOption; } set { this.LineNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of DiscountAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> DiscountAmountOption { get; private set; }

        /// <summary>
        /// Gets or Sets DiscountAmount
        /// </summary>
        [JsonPropertyName("discountAmount")]
        public decimal? DiscountAmount { get { return this.DiscountAmountOption; } set { this.DiscountAmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of AdditionalTaxes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ItemAdditionalTax>?> AdditionalTaxesOption { get; private set; }

        /// <summary>
        /// Gets or Sets AdditionalTaxes
        /// </summary>
        [JsonPropertyName("additionalTaxes")]
        public List<ItemAdditionalTax>? AdditionalTaxes { get { return this.AdditionalTaxesOption; } set { this.AdditionalTaxesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Subquantities
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Subquantity>?> SubquantitiesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Subquantities
        /// </summary>
        [JsonPropertyName("subquantities")]
        public List<Subquantity>? Subquantities { get { return this.SubquantitiesOption; } set { this.SubquantitiesOption = new(value); } }

        /// <summary>
        /// Used to track the state of AlcoholDegree
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> AlcoholDegreeOption { get; private set; }

        /// <summary>
        /// Gets or Sets AlcoholDegree
        /// </summary>
        [JsonPropertyName("alcoholDegree")]
        public decimal? AlcoholDegree { get { return this.AlcoholDegreeOption; } set { this.AlcoholDegreeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Item {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  BillingIndicator: ").Append(BillingIndicator).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  UnitPrice: ").Append(UnitPrice).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  LineNumber: ").Append(LineNumber).Append("\n");
            sb.Append("  DiscountAmount: ").Append(DiscountAmount).Append("\n");
            sb.Append("  AdditionalTaxes: ").Append(AdditionalTaxes).Append("\n");
            sb.Append("  Subquantities: ").Append(Subquantities).Append("\n");
            sb.Append("  AlcoholDegree: ").Append(AlcoholDegree).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 80)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 80.", new [] { "Name" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Item" />
    /// </summary>
    public class ItemJsonConverter : JsonConverter<Item>
    {
        /// <summary>
        /// Deserializes json to <see cref="Item" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Item Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<Item.TypeEnum?> type = default;
            Option<BillingIndicator?> billingIndicator = default;
            Option<string?> quantity = default;
            Option<string?> unitPrice = default;
            Option<decimal?> amount = default;
            Option<int?> lineNumber = default;
            Option<decimal?> discountAmount = default;
            Option<List<ItemAdditionalTax>?> additionalTaxes = default;
            Option<List<Subquantity>?> subquantities = default;
            Option<decimal?> alcoholDegree = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<Item.TypeEnum?>(Item.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "billingIndicator":
                            string? billingIndicatorRawValue = utf8JsonReader.GetString();
                            if (billingIndicatorRawValue != null)
                                billingIndicator = new Option<BillingIndicator?>(BillingIndicatorValueConverter.FromStringOrDefault(billingIndicatorRawValue));
                            break;
                        case "quantity":
                            quantity = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "unitPrice":
                            unitPrice = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "amount":
                            amount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "lineNumber":
                            lineNumber = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "discountAmount":
                            discountAmount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "additionalTaxes":
                            additionalTaxes = new Option<List<ItemAdditionalTax>?>(JsonSerializer.Deserialize<List<ItemAdditionalTax>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "subquantities":
                            subquantities = new Option<List<Subquantity>?>(JsonSerializer.Deserialize<List<Subquantity>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "alcoholDegree":
                            alcoholDegree = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class Item.", nameof(name));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class Item.", nameof(type));

            if (!billingIndicator.IsSet)
                throw new ArgumentException("Property is required for class Item.", nameof(billingIndicator));

            if (!quantity.IsSet)
                throw new ArgumentException("Property is required for class Item.", nameof(quantity));

            if (!unitPrice.IsSet)
                throw new ArgumentException("Property is required for class Item.", nameof(unitPrice));

            if (!amount.IsSet)
                throw new ArgumentException("Property is required for class Item.", nameof(amount));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class Item.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class Item.");

            if (billingIndicator.IsSet && billingIndicator.Value == null)
                throw new ArgumentNullException(nameof(billingIndicator), "Property is not nullable for class Item.");

            if (quantity.IsSet && quantity.Value == null)
                throw new ArgumentNullException(nameof(quantity), "Property is not nullable for class Item.");

            if (unitPrice.IsSet && unitPrice.Value == null)
                throw new ArgumentNullException(nameof(unitPrice), "Property is not nullable for class Item.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class Item.");

            if (lineNumber.IsSet && lineNumber.Value == null)
                throw new ArgumentNullException(nameof(lineNumber), "Property is not nullable for class Item.");

            if (discountAmount.IsSet && discountAmount.Value == null)
                throw new ArgumentNullException(nameof(discountAmount), "Property is not nullable for class Item.");

            if (additionalTaxes.IsSet && additionalTaxes.Value == null)
                throw new ArgumentNullException(nameof(additionalTaxes), "Property is not nullable for class Item.");

            if (subquantities.IsSet && subquantities.Value == null)
                throw new ArgumentNullException(nameof(subquantities), "Property is not nullable for class Item.");

            if (alcoholDegree.IsSet && alcoholDegree.Value == null)
                throw new ArgumentNullException(nameof(alcoholDegree), "Property is not nullable for class Item.");

            return new Item(name.Value!, type.Value!.Value!, billingIndicator.Value!.Value!, quantity.Value!, unitPrice.Value!, amount.Value!.Value!, lineNumber, discountAmount, additionalTaxes, subquantities, alcoholDegree);
        }

        /// <summary>
        /// Serializes a <see cref="Item" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="item"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Item item, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, item, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Item" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="item"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Item item, JsonSerializerOptions jsonSerializerOptions)
        {
            if (item.Name == null)
                throw new ArgumentNullException(nameof(item.Name), "Property is required for class Item.");

            if (item.Quantity == null)
                throw new ArgumentNullException(nameof(item.Quantity), "Property is required for class Item.");

            if (item.UnitPrice == null)
                throw new ArgumentNullException(nameof(item.UnitPrice), "Property is required for class Item.");

            if (item.AdditionalTaxesOption.IsSet && item.AdditionalTaxes == null)
                throw new ArgumentNullException(nameof(item.AdditionalTaxes), "Property is required for class Item.");

            if (item.SubquantitiesOption.IsSet && item.Subquantities == null)
                throw new ArgumentNullException(nameof(item.Subquantities), "Property is required for class Item.");

            writer.WriteString("name", item.Name);

            var typeRawValue = Item.TypeEnumToJsonValue(item.Type);
            writer.WriteString("type", typeRawValue);
            var billingIndicatorRawValue = BillingIndicatorValueConverter.ToJsonValue(item.BillingIndicator);
            writer.WriteString("billingIndicator", billingIndicatorRawValue);

            writer.WriteString("quantity", item.Quantity);

            writer.WriteString("unitPrice", item.UnitPrice);

            writer.WriteNumber("amount", item.Amount);

            if (item.LineNumberOption.IsSet)
                writer.WriteNumber("lineNumber", item.LineNumberOption.Value!.Value);

            if (item.DiscountAmountOption.IsSet)
                writer.WriteNumber("discountAmount", item.DiscountAmountOption.Value!.Value);

            if (item.AdditionalTaxesOption.IsSet)
            {
                writer.WritePropertyName("additionalTaxes");
                JsonSerializer.Serialize(writer, item.AdditionalTaxes, jsonSerializerOptions);
            }
            if (item.SubquantitiesOption.IsSet)
            {
                writer.WritePropertyName("subquantities");
                JsonSerializer.Serialize(writer, item.Subquantities, jsonSerializerOptions);
            }
            if (item.AlcoholDegreeOption.IsSet)
                writer.WriteNumber("alcoholDegree", item.AlcoholDegreeOption.Value!.Value);
        }
    }
}
