/*
 * eCF-Pronesoft Integration API
 *
 * ## Descripción general API de nivel productivo para emitir Comprobantes Fiscales Electrónicos (e-CF) en la República Dominicana a través de la plataforma Pronesoft.  ## Autenticación — OAuth 2.0 Client Credentials  ### Pasos 1. Obtén tus credenciales desde el portal:    - Sandbox: https://ecf.sandbox.pronesoft.com → Apps → Default Sandbox App    - Producción: https://ecf.pronesoft.com → Integraciones → Apps → Crear App 2. Solicita un token via POST /oauth/token — válido por 24 horas (86400s). 3. Usa: Authorization: Bearer <accessToken> en cada request. 4. Renueva al recibir HTTP 401. Buena práctica: renovar 5 minutos antes del vencimiento.  ### Delegación multi-empresa Para actuar en nombre de una empresa asociada (sucursal), agrega:   x-tenant-id: <business-uuid> NO envíes x-tenant-id cuando actúes como la empresa principal.  ### Detalles del Sandbox - Usa cualquier RNC que comience con SBX (ej. SBX123456) — no se requiere certificado real. - Las secuencias son automáticas — no es necesario crearlas manualmente. - El campo environment en el cuerpo del documento DEBE ser TesteCF.  ### Scopes disponibles business:read, business:create, business:update, members:read, members:invite, members:revoke, certificates:read, certificates:upload, certificates:update, documents:read, documents:create, documents:send, documents:receive, documents:update, approvals:read, approvals:commercial, sequences:read, sequences:create, sequences:update, sequences:cancel, business_info:read, certification:read, certification:write, reports:read 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@pronesoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Pronesoft.Ecf.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Pronesoft.Ecf.Sdk.Client.OpenAPIDateConverter;

namespace Pronesoft.Ecf.Sdk.Model
{
    /// <summary>
    /// Payload del evento &#x60;plan.payment_failed&#x60;. Falló el pago automático del plan mensual.
    /// </summary>
    [DataContract(Name = "PlanPaymentFailedPayload")]
    public partial class PlanPaymentFailedPayload : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlanPaymentFailedPayload" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PlanPaymentFailedPayload() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PlanPaymentFailedPayload" /> class.
        /// </summary>
        /// <param name="invoiceId">invoiceId.</param>
        /// <param name="amount">Monto del pago fallido. (required).</param>
        /// <param name="reason">Razón del fallo. (required).</param>
        public PlanPaymentFailedPayload(string invoiceId = default, decimal amount = default, string reason = default)
        {
            this.Amount = amount;
            // to ensure "reason" is required (not null)
            if (reason == null)
            {
                throw new ArgumentNullException("reason is a required property for PlanPaymentFailedPayload and cannot be null");
            }
            this.Reason = reason;
            this.InvoiceId = invoiceId;
        }

        /// <summary>
        /// Gets or Sets InvoiceId
        /// </summary>
        /*
        <example>inv_abc123</example>
        */
        [DataMember(Name = "invoiceId", EmitDefaultValue = true)]
        public string InvoiceId { get; set; }

        /// <summary>
        /// Monto del pago fallido.
        /// </summary>
        /// <value>Monto del pago fallido.</value>
        /*
        <example>4500.0</example>
        */
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public decimal Amount { get; set; }

        /// <summary>
        /// Razón del fallo.
        /// </summary>
        /// <value>Razón del fallo.</value>
        /*
        <example>Fondos insuficientes</example>
        */
        [DataMember(Name = "reason", IsRequired = true, EmitDefaultValue = true)]
        public string Reason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlanPaymentFailedPayload {\n");
            sb.Append("  InvoiceId: ").Append(InvoiceId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
