/*
 * eCF-Pronesoft Integration API
 *
 * ## Descripción general API de nivel productivo para emitir Comprobantes Fiscales Electrónicos (e-CF) en la República Dominicana a través de la plataforma Pronesoft.  ## Autenticación — OAuth 2.0 Client Credentials  ### Pasos 1. Obtén tus credenciales desde el portal:    - Sandbox: https://ecf.sandbox.pronesoft.com → Apps → Default Sandbox App    - Producción: https://ecf.pronesoft.com → Integraciones → Apps → Crear App 2. Solicita un token via POST /oauth/token — válido por 24 horas (86400s). 3. Usa: Authorization: Bearer <accessToken> en cada request. 4. Renueva al recibir HTTP 401. Buena práctica: renovar 5 minutos antes del vencimiento.  ### Delegación multi-empresa Para actuar en nombre de una empresa asociada (sucursal), agrega:   x-tenant-id: <business-uuid> NO envíes x-tenant-id cuando actúes como la empresa principal.  ### Detalles del Sandbox - Usa cualquier RNC que comience con SBX (ej. SBX123456) — no se requiere certificado real. - Las secuencias son automáticas — no es necesario crearlas manualmente. - El campo environment en el cuerpo del documento DEBE ser TesteCF.  ### Scopes disponibles business:read, business:create, business:update, members:read, members:invite, members:revoke, certificates:read, certificates:upload, certificates:update, documents:read, documents:create, documents:send, documents:receive, documents:update, approvals:read, approvals:commercial, sequences:read, sequences:create, sequences:update, sequences:cancel, business_info:read, certification:read, certification:write, reports:read 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@pronesoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Pronesoft.Ecf.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Pronesoft.Ecf.Sdk.Client.OpenAPIDateConverter;

namespace Pronesoft.Ecf.Sdk.Model
{
    /// <summary>
    /// TaxSequence
    /// </summary>
    [DataContract(Name = "TaxSequence")]
    public partial class TaxSequence : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public InvoiceTypeSequence? Type { get; set; }
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum ACTIVE for value: ACTIVE
            /// </summary>
            [EnumMember(Value = "ACTIVE")]
            ACTIVE = 1,

            /// <summary>
            /// Enum EXHAUSTED for value: EXHAUSTED
            /// </summary>
            [EnumMember(Value = "EXHAUSTED")]
            EXHAUSTED = 2,

            /// <summary>
            /// Enum EXPIRED for value: EXPIRED
            /// </summary>
            [EnumMember(Value = "EXPIRED")]
            EXPIRED = 3,

            /// <summary>
            /// Enum VOIDED for value: VOIDED
            /// </summary>
            [EnumMember(Value = "VOIDED")]
            VOIDED = 4
        }


        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TaxSequence" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="type">type.</param>
        /// <param name="startNumber">startNumber.</param>
        /// <param name="endNumber">endNumber.</param>
        /// <param name="currentNumber">currentNumber.</param>
        /// <param name="status">status.</param>
        /// <param name="totalNumbers">totalNumbers.</param>
        /// <param name="usedNumbers">usedNumbers.</param>
        /// <param name="availableNumbers">availableNumbers.</param>
        /// <param name="createdAt">createdAt.</param>
        /// <param name="expiresAt">expiresAt.</param>
        public TaxSequence(string id = default, InvoiceTypeSequence? type = default, string startNumber = default, string endNumber = default, string currentNumber = default, StatusEnum? status = default, int totalNumbers = default, int usedNumbers = default, int availableNumbers = default, DateTime createdAt = default, DateTime expiresAt = default)
        {
            this.Id = id;
            this.Type = type;
            this.StartNumber = startNumber;
            this.EndNumber = endNumber;
            this.CurrentNumber = currentNumber;
            this.Status = status;
            this.TotalNumbers = totalNumbers;
            this.UsedNumbers = usedNumbers;
            this.AvailableNumbers = availableNumbers;
            this.CreatedAt = createdAt;
            this.ExpiresAt = expiresAt;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /*
        <example>seq_sbx_1234567890</example>
        */
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets StartNumber
        /// </summary>
        /*
        <example>E32000000001</example>
        */
        [DataMember(Name = "startNumber", EmitDefaultValue = false)]
        public string StartNumber { get; set; }

        /// <summary>
        /// Gets or Sets EndNumber
        /// </summary>
        /*
        <example>E32000010000</example>
        */
        [DataMember(Name = "endNumber", EmitDefaultValue = false)]
        public string EndNumber { get; set; }

        /// <summary>
        /// Gets or Sets CurrentNumber
        /// </summary>
        /*
        <example>E32000005250</example>
        */
        [DataMember(Name = "currentNumber", EmitDefaultValue = false)]
        public string CurrentNumber { get; set; }

        /// <summary>
        /// Gets or Sets TotalNumbers
        /// </summary>
        [DataMember(Name = "totalNumbers", EmitDefaultValue = false)]
        public int TotalNumbers { get; set; }

        /// <summary>
        /// Gets or Sets UsedNumbers
        /// </summary>
        [DataMember(Name = "usedNumbers", EmitDefaultValue = false)]
        public int UsedNumbers { get; set; }

        /// <summary>
        /// Gets or Sets AvailableNumbers
        /// </summary>
        [DataMember(Name = "availableNumbers", EmitDefaultValue = false)]
        public int AvailableNumbers { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", EmitDefaultValue = false)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets ExpiresAt
        /// </summary>
        [DataMember(Name = "expiresAt", EmitDefaultValue = false)]
        public DateTime ExpiresAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TaxSequence {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  StartNumber: ").Append(StartNumber).Append("\n");
            sb.Append("  EndNumber: ").Append(EndNumber).Append("\n");
            sb.Append("  CurrentNumber: ").Append(CurrentNumber).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  TotalNumbers: ").Append(TotalNumbers).Append("\n");
            sb.Append("  UsedNumbers: ").Append(UsedNumbers).Append("\n");
            sb.Append("  AvailableNumbers: ").Append(AvailableNumbers).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
