<?php
/**
 * TotalsTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PronesoftEcf
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eCF-Pronesoft Master Integration API
 *
 * **Highly detailed** production-grade API specification for eCF-Pronesoft. **Optimized for high-fidelity SDK generation.**  This specification is the result of an exhaustive audit of the source code (NestJS), covering 100% of the DTOs, regex validations, Webhook schemas, and  OAuth 2.0 security flows.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contacto@pronesoft.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace PronesoftEcf\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * TotalsTest Class Doc Comment
 *
 * @category    Class
 * @description Totals
 * @package     PronesoftEcf
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TotalsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Totals"
     */
    public function testTotals()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "taxableAmount"
     */
    public function testPropertyTaxableAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "taxableAmount1"
     */
    public function testPropertyTaxableAmount1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "taxableAmount2"
     */
    public function testPropertyTaxableAmount2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "taxableAmount3"
     */
    public function testPropertyTaxableAmount3()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "exemptAmount"
     */
    public function testPropertyExemptAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "itbisRate1"
     */
    public function testPropertyItbisRate1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "itbisRate2"
     */
    public function testPropertyItbisRate2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "itbisRate3"
     */
    public function testPropertyItbisRate3()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "totalITBIS"
     */
    public function testPropertyTotalITBIS()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "itbis1"
     */
    public function testPropertyItbis1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "itbis2"
     */
    public function testPropertyItbis2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "itbis3"
     */
    public function testPropertyItbis3()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "additionalTaxAmount"
     */
    public function testPropertyAdditionalTaxAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "additionalTaxes"
     */
    public function testPropertyAdditionalTaxes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "totalAmount"
     */
    public function testPropertyTotalAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nonBillableAmount"
     */
    public function testPropertyNonBillableAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "periodAmount"
     */
    public function testPropertyPeriodAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "previousBalance"
     */
    public function testPropertyPreviousBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "advancePaymentAmount"
     */
    public function testPropertyAdvancePaymentAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "amountToPay"
     */
    public function testPropertyAmountToPay()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "totalWithheldITBIS"
     */
    public function testPropertyTotalWithheldITBIS()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "totalIncomeTaxWithholding"
     */
    public function testPropertyTotalIncomeTaxWithholding()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "totalITBISPerception"
     */
    public function testPropertyTotalITBISPerception()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "totalISRPerception"
     */
    public function testPropertyTotalISRPerception()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
