//
// AssociatedCompaniesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

extension PronesoftEcfAPI {


open class AssociatedCompaniesAPI {

    /**
     Create new associated company
     
     - parameter xTenantId: (header) UUID of the company or branch (tenant) making the request. Obtained from the Pronesoft portal after account setup.  
     - parameter email: (form) Owner&#39;s email address (used for login). 
     - parameter password: (form) Initial password for the new account (min 8 characters). 
     - parameter name: (form) Legal business name. 
     - parameter rnc: (form) Company RNC (9 digits) or personal cedula (11 digits). 
     - parameter phone: (form)  
     - parameter address: (form)  
     - parameter city: (form)  
     - parameter country: (form)  
     - parameter firstName: (form)  (optional)
     - parameter lastName: (form)  (optional)
     - parameter jobTitle: (form)  (optional)
     - parameter website: (form)  (optional)
     - parameter category: (form) Business category or industry. (optional)
     - parameter monthlySalesRange: (form) Estimated monthly sales range (e.g. \\\&quot;0-500000\\\&quot;). (optional)
     - parameter printerType: (form)  (optional)
     - parameter logo: (form) Company logo image file (multipart upload). (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createAssociatedCompany(xTenantId: UUID, email: String, password: String, name: String, rnc: String, phone: String, address: String, city: String, country: String, firstName: String? = nil, lastName: String? = nil, jobTitle: String? = nil, website: String? = nil, category: String? = nil, monthlySalesRange: String? = nil, printerType: PrintFormat? = nil, logo: URL? = nil, apiResponseQueue: DispatchQueue = PronesoftEcfAPI.apiResponseQueue, completion: @escaping ((_ data: CreateAssociatedCompany201Response?, _ error: Error?) -> Void)) -> RequestTask {
        return createAssociatedCompanyWithRequestBuilder(xTenantId: xTenantId, email: email, password: password, name: name, rnc: rnc, phone: phone, address: address, city: city, country: country, firstName: firstName, lastName: lastName, jobTitle: jobTitle, website: website, category: category, monthlySalesRange: monthlySalesRange, printerType: printerType, logo: logo).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create new associated company
     - POST /associated-companies
     - Registers a new branch or associated company under the current tenant account. Accepts multipart/form-data to support logo upload. 
     - OAuth:
       - type: oauth2
       - name: oauth2
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter xTenantId: (header) UUID of the company or branch (tenant) making the request. Obtained from the Pronesoft portal after account setup.  
     - parameter email: (form) Owner&#39;s email address (used for login). 
     - parameter password: (form) Initial password for the new account (min 8 characters). 
     - parameter name: (form) Legal business name. 
     - parameter rnc: (form) Company RNC (9 digits) or personal cedula (11 digits). 
     - parameter phone: (form)  
     - parameter address: (form)  
     - parameter city: (form)  
     - parameter country: (form)  
     - parameter firstName: (form)  (optional)
     - parameter lastName: (form)  (optional)
     - parameter jobTitle: (form)  (optional)
     - parameter website: (form)  (optional)
     - parameter category: (form) Business category or industry. (optional)
     - parameter monthlySalesRange: (form) Estimated monthly sales range (e.g. \\\&quot;0-500000\\\&quot;). (optional)
     - parameter printerType: (form)  (optional)
     - parameter logo: (form) Company logo image file (multipart upload). (optional)
     - returns: RequestBuilder<CreateAssociatedCompany201Response> 
     */
    open class func createAssociatedCompanyWithRequestBuilder(xTenantId: UUID, email: String, password: String, name: String, rnc: String, phone: String, address: String, city: String, country: String, firstName: String? = nil, lastName: String? = nil, jobTitle: String? = nil, website: String? = nil, category: String? = nil, monthlySalesRange: String? = nil, printerType: PrintFormat? = nil, logo: URL? = nil) -> RequestBuilder<CreateAssociatedCompany201Response> {
        let localVariablePath = "/associated-companies"
        let localVariableURLString = PronesoftEcfAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "email": email.encodeToJSON(),
            "password": password.encodeToJSON(),
            "firstName": firstName?.encodeToJSON(),
            "lastName": lastName?.encodeToJSON(),
            "jobTitle": jobTitle?.encodeToJSON(),
            "name": name.encodeToJSON(),
            "rnc": rnc.encodeToJSON(),
            "phone": phone.encodeToJSON(),
            "address": address.encodeToJSON(),
            "city": city.encodeToJSON(),
            "country": country.encodeToJSON(),
            "website": website?.encodeToJSON(),
            "category": category?.encodeToJSON(),
            "monthlySalesRange": monthlySalesRange?.encodeToJSON(),
            "printerType": printerType?.encodeToJSON(),
            "logo": logo?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "multipart/form-data",
            "x-tenant-id": xTenantId.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateAssociatedCompany201Response>.Type = PronesoftEcfAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List associated companies / branches
     
     - parameter xTenantId: (header) UUID of the company or branch (tenant) making the request. Obtained from the Pronesoft portal after account setup.  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listAssociatedCompanies(xTenantId: UUID, apiResponseQueue: DispatchQueue = PronesoftEcfAPI.apiResponseQueue, completion: @escaping ((_ data: [AssociatedCompany]?, _ error: Error?) -> Void)) -> RequestTask {
        return listAssociatedCompaniesWithRequestBuilder(xTenantId: xTenantId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List associated companies / branches
     - GET /associated-companies
     - Returns all companies and branches linked to the current tenant.
     - OAuth:
       - type: oauth2
       - name: oauth2
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter xTenantId: (header) UUID of the company or branch (tenant) making the request. Obtained from the Pronesoft portal after account setup.  
     - returns: RequestBuilder<[AssociatedCompany]> 
     */
    open class func listAssociatedCompaniesWithRequestBuilder(xTenantId: UUID) -> RequestBuilder<[AssociatedCompany]> {
        let localVariablePath = "/associated-companies"
        let localVariableURLString = PronesoftEcfAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "x-tenant-id": xTenantId.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[AssociatedCompany]>.Type = PronesoftEcfAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
}
