/*
eCF-Pronesoft Integration API

## Overview Production-grade API for issuing Electronic Tax Receipts (e-CF) in the Dominican Republic through the Pronesoft platform.  ## Authentication — OAuth 2.0 Client Credentials  ### Steps 1. Get credentials from the portal:    - Sandbox: https://ecf.sandbox.pronesoft.com -> Apps -> Default Sandbox App    - Production: https://ecf.pronesoft.com -> Integrations -> Apps -> Create App 2. Request a token via POST /oauth/token — valid for 24 hours (86400s). 3. Use: Authorization: Bearer <accessToken> on every request. 4. Renew on HTTP 401. Best practice: renew 5 minutes before expiry.  ### Multi-company delegation To act on behalf of an associated company (branch), add:   x-tenant-id: <business-uuid> Do NOT send x-tenant-id when acting as the main company.  ### Sandbox specifics - Use any RNC starting with SBX (e.g. SBX123456) — no real certificate needed. - Sequences are automatic — no need to create them manually. - The environment field in the document body MUST be TesteCF.  ### Scopes business:read, business:create, business:update, members:read, members:invite, members:revoke, certificates:read, certificates:upload, certificates:update, documents:read, documents:create, documents:send, documents:receive, documents:update, approvals:read, approvals:commercial, sequences:read, sequences:create, sequences:update, sequences:cancel, business_info:read, certification:read, certification:write, reports:read 

API version: 1.1.0
Contact: support@pronesoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ecf

import (
	"encoding/json"
)

// checks if the Subtotal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Subtotal{}

// Subtotal struct for Subtotal
type Subtotal struct {
	Number *int32 `json:"number,omitempty"`
	Description *string `json:"description,omitempty"`
	Order *int32 `json:"order,omitempty"`
	TaxableAmount *float32 `json:"taxableAmount,omitempty"`
	TaxableAmount1 *float32 `json:"taxableAmount1,omitempty"`
	TaxableAmount2 *float32 `json:"taxableAmount2,omitempty"`
	TaxableAmount3 *float32 `json:"taxableAmount3,omitempty"`
	TotalITBIS *float32 `json:"totalITBIS,omitempty"`
	Itbis1 *float32 `json:"itbis1,omitempty"`
	Itbis2 *float32 `json:"itbis2,omitempty"`
	Itbis3 *float32 `json:"itbis3,omitempty"`
	AdditionalTaxes *float32 `json:"additionalTaxes,omitempty"`
	ExemptAmount *float32 `json:"exemptAmount,omitempty"`
	Amount *float32 `json:"amount,omitempty"`
	Lines *int32 `json:"lines,omitempty"`
}

// NewSubtotal instantiates a new Subtotal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubtotal() *Subtotal {
	this := Subtotal{}
	return &this
}

// NewSubtotalWithDefaults instantiates a new Subtotal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubtotalWithDefaults() *Subtotal {
	this := Subtotal{}
	return &this
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *Subtotal) GetNumber() int32 {
	if o == nil || IsNil(o.Number) {
		var ret int32
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Subtotal) GetNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.Number) {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *Subtotal) HasNumber() bool {
	if o != nil && !IsNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given int32 and assigns it to the Number field.
func (o *Subtotal) SetNumber(v int32) {
	o.Number = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Subtotal) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Subtotal) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Subtotal) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Subtotal) SetDescription(v string) {
	o.Description = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *Subtotal) GetOrder() int32 {
	if o == nil || IsNil(o.Order) {
		var ret int32
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Subtotal) GetOrderOk() (*int32, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *Subtotal) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given int32 and assigns it to the Order field.
func (o *Subtotal) SetOrder(v int32) {
	o.Order = &v
}

// GetTaxableAmount returns the TaxableAmount field value if set, zero value otherwise.
func (o *Subtotal) GetTaxableAmount() float32 {
	if o == nil || IsNil(o.TaxableAmount) {
		var ret float32
		return ret
	}
	return *o.TaxableAmount
}

// GetTaxableAmountOk returns a tuple with the TaxableAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Subtotal) GetTaxableAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.TaxableAmount) {
		return nil, false
	}
	return o.TaxableAmount, true
}

// HasTaxableAmount returns a boolean if a field has been set.
func (o *Subtotal) HasTaxableAmount() bool {
	if o != nil && !IsNil(o.TaxableAmount) {
		return true
	}

	return false
}

// SetTaxableAmount gets a reference to the given float32 and assigns it to the TaxableAmount field.
func (o *Subtotal) SetTaxableAmount(v float32) {
	o.TaxableAmount = &v
}

// GetTaxableAmount1 returns the TaxableAmount1 field value if set, zero value otherwise.
func (o *Subtotal) GetTaxableAmount1() float32 {
	if o == nil || IsNil(o.TaxableAmount1) {
		var ret float32
		return ret
	}
	return *o.TaxableAmount1
}

// GetTaxableAmount1Ok returns a tuple with the TaxableAmount1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Subtotal) GetTaxableAmount1Ok() (*float32, bool) {
	if o == nil || IsNil(o.TaxableAmount1) {
		return nil, false
	}
	return o.TaxableAmount1, true
}

// HasTaxableAmount1 returns a boolean if a field has been set.
func (o *Subtotal) HasTaxableAmount1() bool {
	if o != nil && !IsNil(o.TaxableAmount1) {
		return true
	}

	return false
}

// SetTaxableAmount1 gets a reference to the given float32 and assigns it to the TaxableAmount1 field.
func (o *Subtotal) SetTaxableAmount1(v float32) {
	o.TaxableAmount1 = &v
}

// GetTaxableAmount2 returns the TaxableAmount2 field value if set, zero value otherwise.
func (o *Subtotal) GetTaxableAmount2() float32 {
	if o == nil || IsNil(o.TaxableAmount2) {
		var ret float32
		return ret
	}
	return *o.TaxableAmount2
}

// GetTaxableAmount2Ok returns a tuple with the TaxableAmount2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Subtotal) GetTaxableAmount2Ok() (*float32, bool) {
	if o == nil || IsNil(o.TaxableAmount2) {
		return nil, false
	}
	return o.TaxableAmount2, true
}

// HasTaxableAmount2 returns a boolean if a field has been set.
func (o *Subtotal) HasTaxableAmount2() bool {
	if o != nil && !IsNil(o.TaxableAmount2) {
		return true
	}

	return false
}

// SetTaxableAmount2 gets a reference to the given float32 and assigns it to the TaxableAmount2 field.
func (o *Subtotal) SetTaxableAmount2(v float32) {
	o.TaxableAmount2 = &v
}

// GetTaxableAmount3 returns the TaxableAmount3 field value if set, zero value otherwise.
func (o *Subtotal) GetTaxableAmount3() float32 {
	if o == nil || IsNil(o.TaxableAmount3) {
		var ret float32
		return ret
	}
	return *o.TaxableAmount3
}

// GetTaxableAmount3Ok returns a tuple with the TaxableAmount3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Subtotal) GetTaxableAmount3Ok() (*float32, bool) {
	if o == nil || IsNil(o.TaxableAmount3) {
		return nil, false
	}
	return o.TaxableAmount3, true
}

// HasTaxableAmount3 returns a boolean if a field has been set.
func (o *Subtotal) HasTaxableAmount3() bool {
	if o != nil && !IsNil(o.TaxableAmount3) {
		return true
	}

	return false
}

// SetTaxableAmount3 gets a reference to the given float32 and assigns it to the TaxableAmount3 field.
func (o *Subtotal) SetTaxableAmount3(v float32) {
	o.TaxableAmount3 = &v
}

// GetTotalITBIS returns the TotalITBIS field value if set, zero value otherwise.
func (o *Subtotal) GetTotalITBIS() float32 {
	if o == nil || IsNil(o.TotalITBIS) {
		var ret float32
		return ret
	}
	return *o.TotalITBIS
}

// GetTotalITBISOk returns a tuple with the TotalITBIS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Subtotal) GetTotalITBISOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalITBIS) {
		return nil, false
	}
	return o.TotalITBIS, true
}

// HasTotalITBIS returns a boolean if a field has been set.
func (o *Subtotal) HasTotalITBIS() bool {
	if o != nil && !IsNil(o.TotalITBIS) {
		return true
	}

	return false
}

// SetTotalITBIS gets a reference to the given float32 and assigns it to the TotalITBIS field.
func (o *Subtotal) SetTotalITBIS(v float32) {
	o.TotalITBIS = &v
}

// GetItbis1 returns the Itbis1 field value if set, zero value otherwise.
func (o *Subtotal) GetItbis1() float32 {
	if o == nil || IsNil(o.Itbis1) {
		var ret float32
		return ret
	}
	return *o.Itbis1
}

// GetItbis1Ok returns a tuple with the Itbis1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Subtotal) GetItbis1Ok() (*float32, bool) {
	if o == nil || IsNil(o.Itbis1) {
		return nil, false
	}
	return o.Itbis1, true
}

// HasItbis1 returns a boolean if a field has been set.
func (o *Subtotal) HasItbis1() bool {
	if o != nil && !IsNil(o.Itbis1) {
		return true
	}

	return false
}

// SetItbis1 gets a reference to the given float32 and assigns it to the Itbis1 field.
func (o *Subtotal) SetItbis1(v float32) {
	o.Itbis1 = &v
}

// GetItbis2 returns the Itbis2 field value if set, zero value otherwise.
func (o *Subtotal) GetItbis2() float32 {
	if o == nil || IsNil(o.Itbis2) {
		var ret float32
		return ret
	}
	return *o.Itbis2
}

// GetItbis2Ok returns a tuple with the Itbis2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Subtotal) GetItbis2Ok() (*float32, bool) {
	if o == nil || IsNil(o.Itbis2) {
		return nil, false
	}
	return o.Itbis2, true
}

// HasItbis2 returns a boolean if a field has been set.
func (o *Subtotal) HasItbis2() bool {
	if o != nil && !IsNil(o.Itbis2) {
		return true
	}

	return false
}

// SetItbis2 gets a reference to the given float32 and assigns it to the Itbis2 field.
func (o *Subtotal) SetItbis2(v float32) {
	o.Itbis2 = &v
}

// GetItbis3 returns the Itbis3 field value if set, zero value otherwise.
func (o *Subtotal) GetItbis3() float32 {
	if o == nil || IsNil(o.Itbis3) {
		var ret float32
		return ret
	}
	return *o.Itbis3
}

// GetItbis3Ok returns a tuple with the Itbis3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Subtotal) GetItbis3Ok() (*float32, bool) {
	if o == nil || IsNil(o.Itbis3) {
		return nil, false
	}
	return o.Itbis3, true
}

// HasItbis3 returns a boolean if a field has been set.
func (o *Subtotal) HasItbis3() bool {
	if o != nil && !IsNil(o.Itbis3) {
		return true
	}

	return false
}

// SetItbis3 gets a reference to the given float32 and assigns it to the Itbis3 field.
func (o *Subtotal) SetItbis3(v float32) {
	o.Itbis3 = &v
}

// GetAdditionalTaxes returns the AdditionalTaxes field value if set, zero value otherwise.
func (o *Subtotal) GetAdditionalTaxes() float32 {
	if o == nil || IsNil(o.AdditionalTaxes) {
		var ret float32
		return ret
	}
	return *o.AdditionalTaxes
}

// GetAdditionalTaxesOk returns a tuple with the AdditionalTaxes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Subtotal) GetAdditionalTaxesOk() (*float32, bool) {
	if o == nil || IsNil(o.AdditionalTaxes) {
		return nil, false
	}
	return o.AdditionalTaxes, true
}

// HasAdditionalTaxes returns a boolean if a field has been set.
func (o *Subtotal) HasAdditionalTaxes() bool {
	if o != nil && !IsNil(o.AdditionalTaxes) {
		return true
	}

	return false
}

// SetAdditionalTaxes gets a reference to the given float32 and assigns it to the AdditionalTaxes field.
func (o *Subtotal) SetAdditionalTaxes(v float32) {
	o.AdditionalTaxes = &v
}

// GetExemptAmount returns the ExemptAmount field value if set, zero value otherwise.
func (o *Subtotal) GetExemptAmount() float32 {
	if o == nil || IsNil(o.ExemptAmount) {
		var ret float32
		return ret
	}
	return *o.ExemptAmount
}

// GetExemptAmountOk returns a tuple with the ExemptAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Subtotal) GetExemptAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.ExemptAmount) {
		return nil, false
	}
	return o.ExemptAmount, true
}

// HasExemptAmount returns a boolean if a field has been set.
func (o *Subtotal) HasExemptAmount() bool {
	if o != nil && !IsNil(o.ExemptAmount) {
		return true
	}

	return false
}

// SetExemptAmount gets a reference to the given float32 and assigns it to the ExemptAmount field.
func (o *Subtotal) SetExemptAmount(v float32) {
	o.ExemptAmount = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *Subtotal) GetAmount() float32 {
	if o == nil || IsNil(o.Amount) {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Subtotal) GetAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *Subtotal) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *Subtotal) SetAmount(v float32) {
	o.Amount = &v
}

// GetLines returns the Lines field value if set, zero value otherwise.
func (o *Subtotal) GetLines() int32 {
	if o == nil || IsNil(o.Lines) {
		var ret int32
		return ret
	}
	return *o.Lines
}

// GetLinesOk returns a tuple with the Lines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Subtotal) GetLinesOk() (*int32, bool) {
	if o == nil || IsNil(o.Lines) {
		return nil, false
	}
	return o.Lines, true
}

// HasLines returns a boolean if a field has been set.
func (o *Subtotal) HasLines() bool {
	if o != nil && !IsNil(o.Lines) {
		return true
	}

	return false
}

// SetLines gets a reference to the given int32 and assigns it to the Lines field.
func (o *Subtotal) SetLines(v int32) {
	o.Lines = &v
}

func (o Subtotal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Subtotal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Number) {
		toSerialize["number"] = o.Number
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.TaxableAmount) {
		toSerialize["taxableAmount"] = o.TaxableAmount
	}
	if !IsNil(o.TaxableAmount1) {
		toSerialize["taxableAmount1"] = o.TaxableAmount1
	}
	if !IsNil(o.TaxableAmount2) {
		toSerialize["taxableAmount2"] = o.TaxableAmount2
	}
	if !IsNil(o.TaxableAmount3) {
		toSerialize["taxableAmount3"] = o.TaxableAmount3
	}
	if !IsNil(o.TotalITBIS) {
		toSerialize["totalITBIS"] = o.TotalITBIS
	}
	if !IsNil(o.Itbis1) {
		toSerialize["itbis1"] = o.Itbis1
	}
	if !IsNil(o.Itbis2) {
		toSerialize["itbis2"] = o.Itbis2
	}
	if !IsNil(o.Itbis3) {
		toSerialize["itbis3"] = o.Itbis3
	}
	if !IsNil(o.AdditionalTaxes) {
		toSerialize["additionalTaxes"] = o.AdditionalTaxes
	}
	if !IsNil(o.ExemptAmount) {
		toSerialize["exemptAmount"] = o.ExemptAmount
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Lines) {
		toSerialize["lines"] = o.Lines
	}
	return toSerialize, nil
}

type NullableSubtotal struct {
	value *Subtotal
	isSet bool
}

func (v NullableSubtotal) Get() *Subtotal {
	return v.value
}

func (v *NullableSubtotal) Set(val *Subtotal) {
	v.value = val
	v.isSet = true
}

func (v NullableSubtotal) IsSet() bool {
	return v.isSet
}

func (v *NullableSubtotal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubtotal(val *Subtotal) *NullableSubtotal {
	return &NullableSubtotal{value: val, isSet: true}
}

func (v NullableSubtotal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubtotal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


