/*
eCF-Pronesoft Integration API

## Descripción general API de nivel productivo para emitir Comprobantes Fiscales Electrónicos (e-CF) en la República Dominicana a través de la plataforma Pronesoft.  ## Autenticación — OAuth 2.0 Client Credentials  ### Pasos 1. Obtén tus credenciales desde el portal:    - Sandbox: https://ecf.sandbox.pronesoft.com → Apps → Default Sandbox App    - Producción: https://ecf.pronesoft.com → Integraciones → Apps → Crear App 2. Solicita un token via POST /oauth/token — válido por 24 horas (86400s). 3. Usa: Authorization: Bearer <accessToken> en cada request. 4. Renueva al recibir HTTP 401. Buena práctica: renovar 5 minutos antes del vencimiento.  ### Delegación multi-empresa Para actuar en nombre de una empresa asociada (sucursal), agrega:   x-tenant-id: <business-uuid> NO envíes x-tenant-id cuando actúes como la empresa principal.  ### Detalles del Sandbox - Usa cualquier RNC que comience con SBX (ej. SBX123456) — no se requiere certificado real. - Las secuencias son automáticas — no es necesario crearlas manualmente. - El campo environment en el cuerpo del documento DEBE ser TesteCF.  ### Scopes disponibles business:read, business:create, business:update, members:read, members:invite, members:revoke, certificates:read, certificates:upload, certificates:update, documents:read, documents:create, documents:send, documents:receive, documents:update, approvals:read, approvals:commercial, sequences:read, sequences:create, sequences:update, sequences:cancel, business_info:read, certification:read, certification:write, reports:read 

API version: 1.2.0
Contact: support@pronesoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the EcfStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EcfStatusResponse{}

// EcfStatusResponse Respuesta del endpoint GET /ecf/status/{id}. Incluye el estado fiscal completo de DGII.
type EcfStatusResponse struct {
	// ID interno del documento.
	Id string `json:"id"`
	// Fecha de emisión del documento (YYYY-MM-DD).
	StampDate NullableString `json:"stampDate,omitempty"`
	// Estado del proceso de envío a DGII.
	Status string `json:"status"`
	// Estado fiscal según la respuesta de DGII. null mientras no hay respuesta.
	LegalStatus NullableString `json:"legalStatus,omitempty"`
	CompanyIdentification EcfSubmitResponseCompanyIdentification `json:"companyIdentification"`
	// ID de seguimiento asignado por DGII.
	TrackId NullableString `json:"trackId,omitempty"`
	// Número de control electrónico (e-NCF).
	DocumentNumber NullableString `json:"documentNumber,omitempty"`
	// Número e-NCF del documento.
	Encf NullableString `json:"encf,omitempty"`
	// true si fue emitido en modo contingencia.
	ContingencyMode *bool `json:"contingencyMode,omitempty"`
	// Mensaje oficial DGII cuando contingencyMode es true.
	ContingencyMessage *string `json:"contingencyMessage,omitempty"`
	// URL del código QR del documento.
	DocumentStampUrl NullableString `json:"documentStampUrl,omitempty"`
	// URL pre-firmada del PDF (expira en 1 hora).
	Pdf NullableString `json:"pdf,omitempty"`
	// URL pre-firmada del XML firmado (expira en 1 hora).
	XmlUrl NullableString `json:"xmlUrl,omitempty"`
	// Fecha y hora de la firma digital.
	SignatureDate NullableTime `json:"signatureDate,omitempty"`
	// Código de seguridad del documento.
	SecurityCode NullableString `json:"securityCode,omitempty"`
	// true si DGII confirmó el consumo de la secuencia.
	SequenceConsumed bool `json:"sequenceConsumed"`
	// Respuesta completa de DGII (disponible cuando status es FINISHED).
	GovernmentResponse map[string]interface{} `json:"governmentResponse,omitempty"`
}

type _EcfStatusResponse EcfStatusResponse

// NewEcfStatusResponse instantiates a new EcfStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEcfStatusResponse(id string, status string, companyIdentification EcfSubmitResponseCompanyIdentification, sequenceConsumed bool) *EcfStatusResponse {
	this := EcfStatusResponse{}
	this.Id = id
	this.Status = status
	this.CompanyIdentification = companyIdentification
	this.SequenceConsumed = sequenceConsumed
	return &this
}

// NewEcfStatusResponseWithDefaults instantiates a new EcfStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEcfStatusResponseWithDefaults() *EcfStatusResponse {
	this := EcfStatusResponse{}
	return &this
}

// GetId returns the Id field value
func (o *EcfStatusResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EcfStatusResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EcfStatusResponse) SetId(v string) {
	o.Id = v
}

// GetStampDate returns the StampDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EcfStatusResponse) GetStampDate() string {
	if o == nil || IsNil(o.StampDate.Get()) {
		var ret string
		return ret
	}
	return *o.StampDate.Get()
}

// GetStampDateOk returns a tuple with the StampDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EcfStatusResponse) GetStampDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StampDate.Get(), o.StampDate.IsSet()
}

// HasStampDate returns a boolean if a field has been set.
func (o *EcfStatusResponse) HasStampDate() bool {
	if o != nil && o.StampDate.IsSet() {
		return true
	}

	return false
}

// SetStampDate gets a reference to the given NullableString and assigns it to the StampDate field.
func (o *EcfStatusResponse) SetStampDate(v string) {
	o.StampDate.Set(&v)
}
// SetStampDateNil sets the value for StampDate to be an explicit nil
func (o *EcfStatusResponse) SetStampDateNil() {
	o.StampDate.Set(nil)
}

// UnsetStampDate ensures that no value is present for StampDate, not even an explicit nil
func (o *EcfStatusResponse) UnsetStampDate() {
	o.StampDate.Unset()
}

// GetStatus returns the Status field value
func (o *EcfStatusResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *EcfStatusResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *EcfStatusResponse) SetStatus(v string) {
	o.Status = v
}

// GetLegalStatus returns the LegalStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EcfStatusResponse) GetLegalStatus() string {
	if o == nil || IsNil(o.LegalStatus.Get()) {
		var ret string
		return ret
	}
	return *o.LegalStatus.Get()
}

// GetLegalStatusOk returns a tuple with the LegalStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EcfStatusResponse) GetLegalStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LegalStatus.Get(), o.LegalStatus.IsSet()
}

// HasLegalStatus returns a boolean if a field has been set.
func (o *EcfStatusResponse) HasLegalStatus() bool {
	if o != nil && o.LegalStatus.IsSet() {
		return true
	}

	return false
}

// SetLegalStatus gets a reference to the given NullableString and assigns it to the LegalStatus field.
func (o *EcfStatusResponse) SetLegalStatus(v string) {
	o.LegalStatus.Set(&v)
}
// SetLegalStatusNil sets the value for LegalStatus to be an explicit nil
func (o *EcfStatusResponse) SetLegalStatusNil() {
	o.LegalStatus.Set(nil)
}

// UnsetLegalStatus ensures that no value is present for LegalStatus, not even an explicit nil
func (o *EcfStatusResponse) UnsetLegalStatus() {
	o.LegalStatus.Unset()
}

// GetCompanyIdentification returns the CompanyIdentification field value
func (o *EcfStatusResponse) GetCompanyIdentification() EcfSubmitResponseCompanyIdentification {
	if o == nil {
		var ret EcfSubmitResponseCompanyIdentification
		return ret
	}

	return o.CompanyIdentification
}

// GetCompanyIdentificationOk returns a tuple with the CompanyIdentification field value
// and a boolean to check if the value has been set.
func (o *EcfStatusResponse) GetCompanyIdentificationOk() (*EcfSubmitResponseCompanyIdentification, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompanyIdentification, true
}

// SetCompanyIdentification sets field value
func (o *EcfStatusResponse) SetCompanyIdentification(v EcfSubmitResponseCompanyIdentification) {
	o.CompanyIdentification = v
}

// GetTrackId returns the TrackId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EcfStatusResponse) GetTrackId() string {
	if o == nil || IsNil(o.TrackId.Get()) {
		var ret string
		return ret
	}
	return *o.TrackId.Get()
}

// GetTrackIdOk returns a tuple with the TrackId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EcfStatusResponse) GetTrackIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TrackId.Get(), o.TrackId.IsSet()
}

// HasTrackId returns a boolean if a field has been set.
func (o *EcfStatusResponse) HasTrackId() bool {
	if o != nil && o.TrackId.IsSet() {
		return true
	}

	return false
}

// SetTrackId gets a reference to the given NullableString and assigns it to the TrackId field.
func (o *EcfStatusResponse) SetTrackId(v string) {
	o.TrackId.Set(&v)
}
// SetTrackIdNil sets the value for TrackId to be an explicit nil
func (o *EcfStatusResponse) SetTrackIdNil() {
	o.TrackId.Set(nil)
}

// UnsetTrackId ensures that no value is present for TrackId, not even an explicit nil
func (o *EcfStatusResponse) UnsetTrackId() {
	o.TrackId.Unset()
}

// GetDocumentNumber returns the DocumentNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EcfStatusResponse) GetDocumentNumber() string {
	if o == nil || IsNil(o.DocumentNumber.Get()) {
		var ret string
		return ret
	}
	return *o.DocumentNumber.Get()
}

// GetDocumentNumberOk returns a tuple with the DocumentNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EcfStatusResponse) GetDocumentNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DocumentNumber.Get(), o.DocumentNumber.IsSet()
}

// HasDocumentNumber returns a boolean if a field has been set.
func (o *EcfStatusResponse) HasDocumentNumber() bool {
	if o != nil && o.DocumentNumber.IsSet() {
		return true
	}

	return false
}

// SetDocumentNumber gets a reference to the given NullableString and assigns it to the DocumentNumber field.
func (o *EcfStatusResponse) SetDocumentNumber(v string) {
	o.DocumentNumber.Set(&v)
}
// SetDocumentNumberNil sets the value for DocumentNumber to be an explicit nil
func (o *EcfStatusResponse) SetDocumentNumberNil() {
	o.DocumentNumber.Set(nil)
}

// UnsetDocumentNumber ensures that no value is present for DocumentNumber, not even an explicit nil
func (o *EcfStatusResponse) UnsetDocumentNumber() {
	o.DocumentNumber.Unset()
}

// GetEncf returns the Encf field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EcfStatusResponse) GetEncf() string {
	if o == nil || IsNil(o.Encf.Get()) {
		var ret string
		return ret
	}
	return *o.Encf.Get()
}

// GetEncfOk returns a tuple with the Encf field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EcfStatusResponse) GetEncfOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Encf.Get(), o.Encf.IsSet()
}

// HasEncf returns a boolean if a field has been set.
func (o *EcfStatusResponse) HasEncf() bool {
	if o != nil && o.Encf.IsSet() {
		return true
	}

	return false
}

// SetEncf gets a reference to the given NullableString and assigns it to the Encf field.
func (o *EcfStatusResponse) SetEncf(v string) {
	o.Encf.Set(&v)
}
// SetEncfNil sets the value for Encf to be an explicit nil
func (o *EcfStatusResponse) SetEncfNil() {
	o.Encf.Set(nil)
}

// UnsetEncf ensures that no value is present for Encf, not even an explicit nil
func (o *EcfStatusResponse) UnsetEncf() {
	o.Encf.Unset()
}

// GetContingencyMode returns the ContingencyMode field value if set, zero value otherwise.
func (o *EcfStatusResponse) GetContingencyMode() bool {
	if o == nil || IsNil(o.ContingencyMode) {
		var ret bool
		return ret
	}
	return *o.ContingencyMode
}

// GetContingencyModeOk returns a tuple with the ContingencyMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EcfStatusResponse) GetContingencyModeOk() (*bool, bool) {
	if o == nil || IsNil(o.ContingencyMode) {
		return nil, false
	}
	return o.ContingencyMode, true
}

// HasContingencyMode returns a boolean if a field has been set.
func (o *EcfStatusResponse) HasContingencyMode() bool {
	if o != nil && !IsNil(o.ContingencyMode) {
		return true
	}

	return false
}

// SetContingencyMode gets a reference to the given bool and assigns it to the ContingencyMode field.
func (o *EcfStatusResponse) SetContingencyMode(v bool) {
	o.ContingencyMode = &v
}

// GetContingencyMessage returns the ContingencyMessage field value if set, zero value otherwise.
func (o *EcfStatusResponse) GetContingencyMessage() string {
	if o == nil || IsNil(o.ContingencyMessage) {
		var ret string
		return ret
	}
	return *o.ContingencyMessage
}

// GetContingencyMessageOk returns a tuple with the ContingencyMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EcfStatusResponse) GetContingencyMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ContingencyMessage) {
		return nil, false
	}
	return o.ContingencyMessage, true
}

// HasContingencyMessage returns a boolean if a field has been set.
func (o *EcfStatusResponse) HasContingencyMessage() bool {
	if o != nil && !IsNil(o.ContingencyMessage) {
		return true
	}

	return false
}

// SetContingencyMessage gets a reference to the given string and assigns it to the ContingencyMessage field.
func (o *EcfStatusResponse) SetContingencyMessage(v string) {
	o.ContingencyMessage = &v
}

// GetDocumentStampUrl returns the DocumentStampUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EcfStatusResponse) GetDocumentStampUrl() string {
	if o == nil || IsNil(o.DocumentStampUrl.Get()) {
		var ret string
		return ret
	}
	return *o.DocumentStampUrl.Get()
}

// GetDocumentStampUrlOk returns a tuple with the DocumentStampUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EcfStatusResponse) GetDocumentStampUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DocumentStampUrl.Get(), o.DocumentStampUrl.IsSet()
}

// HasDocumentStampUrl returns a boolean if a field has been set.
func (o *EcfStatusResponse) HasDocumentStampUrl() bool {
	if o != nil && o.DocumentStampUrl.IsSet() {
		return true
	}

	return false
}

// SetDocumentStampUrl gets a reference to the given NullableString and assigns it to the DocumentStampUrl field.
func (o *EcfStatusResponse) SetDocumentStampUrl(v string) {
	o.DocumentStampUrl.Set(&v)
}
// SetDocumentStampUrlNil sets the value for DocumentStampUrl to be an explicit nil
func (o *EcfStatusResponse) SetDocumentStampUrlNil() {
	o.DocumentStampUrl.Set(nil)
}

// UnsetDocumentStampUrl ensures that no value is present for DocumentStampUrl, not even an explicit nil
func (o *EcfStatusResponse) UnsetDocumentStampUrl() {
	o.DocumentStampUrl.Unset()
}

// GetPdf returns the Pdf field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EcfStatusResponse) GetPdf() string {
	if o == nil || IsNil(o.Pdf.Get()) {
		var ret string
		return ret
	}
	return *o.Pdf.Get()
}

// GetPdfOk returns a tuple with the Pdf field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EcfStatusResponse) GetPdfOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pdf.Get(), o.Pdf.IsSet()
}

// HasPdf returns a boolean if a field has been set.
func (o *EcfStatusResponse) HasPdf() bool {
	if o != nil && o.Pdf.IsSet() {
		return true
	}

	return false
}

// SetPdf gets a reference to the given NullableString and assigns it to the Pdf field.
func (o *EcfStatusResponse) SetPdf(v string) {
	o.Pdf.Set(&v)
}
// SetPdfNil sets the value for Pdf to be an explicit nil
func (o *EcfStatusResponse) SetPdfNil() {
	o.Pdf.Set(nil)
}

// UnsetPdf ensures that no value is present for Pdf, not even an explicit nil
func (o *EcfStatusResponse) UnsetPdf() {
	o.Pdf.Unset()
}

// GetXmlUrl returns the XmlUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EcfStatusResponse) GetXmlUrl() string {
	if o == nil || IsNil(o.XmlUrl.Get()) {
		var ret string
		return ret
	}
	return *o.XmlUrl.Get()
}

// GetXmlUrlOk returns a tuple with the XmlUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EcfStatusResponse) GetXmlUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.XmlUrl.Get(), o.XmlUrl.IsSet()
}

// HasXmlUrl returns a boolean if a field has been set.
func (o *EcfStatusResponse) HasXmlUrl() bool {
	if o != nil && o.XmlUrl.IsSet() {
		return true
	}

	return false
}

// SetXmlUrl gets a reference to the given NullableString and assigns it to the XmlUrl field.
func (o *EcfStatusResponse) SetXmlUrl(v string) {
	o.XmlUrl.Set(&v)
}
// SetXmlUrlNil sets the value for XmlUrl to be an explicit nil
func (o *EcfStatusResponse) SetXmlUrlNil() {
	o.XmlUrl.Set(nil)
}

// UnsetXmlUrl ensures that no value is present for XmlUrl, not even an explicit nil
func (o *EcfStatusResponse) UnsetXmlUrl() {
	o.XmlUrl.Unset()
}

// GetSignatureDate returns the SignatureDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EcfStatusResponse) GetSignatureDate() time.Time {
	if o == nil || IsNil(o.SignatureDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.SignatureDate.Get()
}

// GetSignatureDateOk returns a tuple with the SignatureDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EcfStatusResponse) GetSignatureDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.SignatureDate.Get(), o.SignatureDate.IsSet()
}

// HasSignatureDate returns a boolean if a field has been set.
func (o *EcfStatusResponse) HasSignatureDate() bool {
	if o != nil && o.SignatureDate.IsSet() {
		return true
	}

	return false
}

// SetSignatureDate gets a reference to the given NullableTime and assigns it to the SignatureDate field.
func (o *EcfStatusResponse) SetSignatureDate(v time.Time) {
	o.SignatureDate.Set(&v)
}
// SetSignatureDateNil sets the value for SignatureDate to be an explicit nil
func (o *EcfStatusResponse) SetSignatureDateNil() {
	o.SignatureDate.Set(nil)
}

// UnsetSignatureDate ensures that no value is present for SignatureDate, not even an explicit nil
func (o *EcfStatusResponse) UnsetSignatureDate() {
	o.SignatureDate.Unset()
}

// GetSecurityCode returns the SecurityCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EcfStatusResponse) GetSecurityCode() string {
	if o == nil || IsNil(o.SecurityCode.Get()) {
		var ret string
		return ret
	}
	return *o.SecurityCode.Get()
}

// GetSecurityCodeOk returns a tuple with the SecurityCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EcfStatusResponse) GetSecurityCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SecurityCode.Get(), o.SecurityCode.IsSet()
}

// HasSecurityCode returns a boolean if a field has been set.
func (o *EcfStatusResponse) HasSecurityCode() bool {
	if o != nil && o.SecurityCode.IsSet() {
		return true
	}

	return false
}

// SetSecurityCode gets a reference to the given NullableString and assigns it to the SecurityCode field.
func (o *EcfStatusResponse) SetSecurityCode(v string) {
	o.SecurityCode.Set(&v)
}
// SetSecurityCodeNil sets the value for SecurityCode to be an explicit nil
func (o *EcfStatusResponse) SetSecurityCodeNil() {
	o.SecurityCode.Set(nil)
}

// UnsetSecurityCode ensures that no value is present for SecurityCode, not even an explicit nil
func (o *EcfStatusResponse) UnsetSecurityCode() {
	o.SecurityCode.Unset()
}

// GetSequenceConsumed returns the SequenceConsumed field value
func (o *EcfStatusResponse) GetSequenceConsumed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SequenceConsumed
}

// GetSequenceConsumedOk returns a tuple with the SequenceConsumed field value
// and a boolean to check if the value has been set.
func (o *EcfStatusResponse) GetSequenceConsumedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SequenceConsumed, true
}

// SetSequenceConsumed sets field value
func (o *EcfStatusResponse) SetSequenceConsumed(v bool) {
	o.SequenceConsumed = v
}

// GetGovernmentResponse returns the GovernmentResponse field value if set, zero value otherwise.
func (o *EcfStatusResponse) GetGovernmentResponse() map[string]interface{} {
	if o == nil || IsNil(o.GovernmentResponse) {
		var ret map[string]interface{}
		return ret
	}
	return o.GovernmentResponse
}

// GetGovernmentResponseOk returns a tuple with the GovernmentResponse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EcfStatusResponse) GetGovernmentResponseOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.GovernmentResponse) {
		return map[string]interface{}{}, false
	}
	return o.GovernmentResponse, true
}

// HasGovernmentResponse returns a boolean if a field has been set.
func (o *EcfStatusResponse) HasGovernmentResponse() bool {
	if o != nil && !IsNil(o.GovernmentResponse) {
		return true
	}

	return false
}

// SetGovernmentResponse gets a reference to the given map[string]interface{} and assigns it to the GovernmentResponse field.
func (o *EcfStatusResponse) SetGovernmentResponse(v map[string]interface{}) {
	o.GovernmentResponse = v
}

func (o EcfStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EcfStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if o.StampDate.IsSet() {
		toSerialize["stampDate"] = o.StampDate.Get()
	}
	toSerialize["status"] = o.Status
	if o.LegalStatus.IsSet() {
		toSerialize["legalStatus"] = o.LegalStatus.Get()
	}
	toSerialize["companyIdentification"] = o.CompanyIdentification
	if o.TrackId.IsSet() {
		toSerialize["trackId"] = o.TrackId.Get()
	}
	if o.DocumentNumber.IsSet() {
		toSerialize["documentNumber"] = o.DocumentNumber.Get()
	}
	if o.Encf.IsSet() {
		toSerialize["encf"] = o.Encf.Get()
	}
	if !IsNil(o.ContingencyMode) {
		toSerialize["contingencyMode"] = o.ContingencyMode
	}
	if !IsNil(o.ContingencyMessage) {
		toSerialize["contingencyMessage"] = o.ContingencyMessage
	}
	if o.DocumentStampUrl.IsSet() {
		toSerialize["documentStampUrl"] = o.DocumentStampUrl.Get()
	}
	if o.Pdf.IsSet() {
		toSerialize["pdf"] = o.Pdf.Get()
	}
	if o.XmlUrl.IsSet() {
		toSerialize["xmlUrl"] = o.XmlUrl.Get()
	}
	if o.SignatureDate.IsSet() {
		toSerialize["signatureDate"] = o.SignatureDate.Get()
	}
	if o.SecurityCode.IsSet() {
		toSerialize["securityCode"] = o.SecurityCode.Get()
	}
	toSerialize["sequenceConsumed"] = o.SequenceConsumed
	if !IsNil(o.GovernmentResponse) {
		toSerialize["governmentResponse"] = o.GovernmentResponse
	}
	return toSerialize, nil
}

func (o *EcfStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"companyIdentification",
		"sequenceConsumed",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEcfStatusResponse := _EcfStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEcfStatusResponse)

	if err != nil {
		return err
	}

	*o = EcfStatusResponse(varEcfStatusResponse)

	return err
}

type NullableEcfStatusResponse struct {
	value *EcfStatusResponse
	isSet bool
}

func (v NullableEcfStatusResponse) Get() *EcfStatusResponse {
	return v.value
}

func (v *NullableEcfStatusResponse) Set(val *EcfStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEcfStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEcfStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEcfStatusResponse(val *EcfStatusResponse) *NullableEcfStatusResponse {
	return &NullableEcfStatusResponse{value: val, isSet: true}
}

func (v NullableEcfStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEcfStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


