/*
eCF-Pronesoft Integration API

## Overview Production-grade API for issuing Electronic Tax Receipts (e-CF) in the Dominican Republic through the Pronesoft platform.  ## Authentication — OAuth 2.0 Client Credentials  ### Steps 1. Get credentials from the portal:    - Sandbox: https://ecf.sandbox.pronesoft.com -> Apps -> Default Sandbox App    - Production: https://ecf.pronesoft.com -> Integrations -> Apps -> Create App 2. Request a token via POST /oauth/token — valid for 24 hours (86400s). 3. Use: Authorization: Bearer <accessToken> on every request. 4. Renew on HTTP 401. Best practice: renew 5 minutes before expiry.  ### Multi-company delegation To act on behalf of an associated company (branch), add:   x-tenant-id: <business-uuid> Do NOT send x-tenant-id when acting as the main company.  ### Sandbox specifics - Use any RNC starting with SBX (e.g. SBX123456) — no real certificate needed. - Sequences are automatic — no need to create them manually. - The environment field in the document body MUST be TesteCF.  ### Scopes business:read, business:create, business:update, members:read, members:invite, members:revoke, certificates:read, certificates:upload, certificates:update, documents:read, documents:create, documents:send, documents:receive, documents:update, approvals:read, approvals:commercial, sequences:read, sequences:create, sequences:update, sequences:cancel, business_info:read, certification:read, certification:write, reports:read 

API version: 1.1.0
Contact: support@pronesoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ecf

import (
	"encoding/json"
)

// checks if the CompanyMetricsDocumentsStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompanyMetricsDocumentsStatus{}

// CompanyMetricsDocumentsStatus struct for CompanyMetricsDocumentsStatus
type CompanyMetricsDocumentsStatus struct {
	APPROVED *int32 `json:"APPROVED,omitempty"`
	REJECTED *int32 `json:"REJECTED,omitempty"`
	PENDING *int32 `json:"PENDING,omitempty"`
}

// NewCompanyMetricsDocumentsStatus instantiates a new CompanyMetricsDocumentsStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompanyMetricsDocumentsStatus() *CompanyMetricsDocumentsStatus {
	this := CompanyMetricsDocumentsStatus{}
	return &this
}

// NewCompanyMetricsDocumentsStatusWithDefaults instantiates a new CompanyMetricsDocumentsStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyMetricsDocumentsStatusWithDefaults() *CompanyMetricsDocumentsStatus {
	this := CompanyMetricsDocumentsStatus{}
	return &this
}

// GetAPPROVED returns the APPROVED field value if set, zero value otherwise.
func (o *CompanyMetricsDocumentsStatus) GetAPPROVED() int32 {
	if o == nil || IsNil(o.APPROVED) {
		var ret int32
		return ret
	}
	return *o.APPROVED
}

// GetAPPROVEDOk returns a tuple with the APPROVED field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyMetricsDocumentsStatus) GetAPPROVEDOk() (*int32, bool) {
	if o == nil || IsNil(o.APPROVED) {
		return nil, false
	}
	return o.APPROVED, true
}

// HasAPPROVED returns a boolean if a field has been set.
func (o *CompanyMetricsDocumentsStatus) HasAPPROVED() bool {
	if o != nil && !IsNil(o.APPROVED) {
		return true
	}

	return false
}

// SetAPPROVED gets a reference to the given int32 and assigns it to the APPROVED field.
func (o *CompanyMetricsDocumentsStatus) SetAPPROVED(v int32) {
	o.APPROVED = &v
}

// GetREJECTED returns the REJECTED field value if set, zero value otherwise.
func (o *CompanyMetricsDocumentsStatus) GetREJECTED() int32 {
	if o == nil || IsNil(o.REJECTED) {
		var ret int32
		return ret
	}
	return *o.REJECTED
}

// GetREJECTEDOk returns a tuple with the REJECTED field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyMetricsDocumentsStatus) GetREJECTEDOk() (*int32, bool) {
	if o == nil || IsNil(o.REJECTED) {
		return nil, false
	}
	return o.REJECTED, true
}

// HasREJECTED returns a boolean if a field has been set.
func (o *CompanyMetricsDocumentsStatus) HasREJECTED() bool {
	if o != nil && !IsNil(o.REJECTED) {
		return true
	}

	return false
}

// SetREJECTED gets a reference to the given int32 and assigns it to the REJECTED field.
func (o *CompanyMetricsDocumentsStatus) SetREJECTED(v int32) {
	o.REJECTED = &v
}

// GetPENDING returns the PENDING field value if set, zero value otherwise.
func (o *CompanyMetricsDocumentsStatus) GetPENDING() int32 {
	if o == nil || IsNil(o.PENDING) {
		var ret int32
		return ret
	}
	return *o.PENDING
}

// GetPENDINGOk returns a tuple with the PENDING field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyMetricsDocumentsStatus) GetPENDINGOk() (*int32, bool) {
	if o == nil || IsNil(o.PENDING) {
		return nil, false
	}
	return o.PENDING, true
}

// HasPENDING returns a boolean if a field has been set.
func (o *CompanyMetricsDocumentsStatus) HasPENDING() bool {
	if o != nil && !IsNil(o.PENDING) {
		return true
	}

	return false
}

// SetPENDING gets a reference to the given int32 and assigns it to the PENDING field.
func (o *CompanyMetricsDocumentsStatus) SetPENDING(v int32) {
	o.PENDING = &v
}

func (o CompanyMetricsDocumentsStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompanyMetricsDocumentsStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.APPROVED) {
		toSerialize["APPROVED"] = o.APPROVED
	}
	if !IsNil(o.REJECTED) {
		toSerialize["REJECTED"] = o.REJECTED
	}
	if !IsNil(o.PENDING) {
		toSerialize["PENDING"] = o.PENDING
	}
	return toSerialize, nil
}

type NullableCompanyMetricsDocumentsStatus struct {
	value *CompanyMetricsDocumentsStatus
	isSet bool
}

func (v NullableCompanyMetricsDocumentsStatus) Get() *CompanyMetricsDocumentsStatus {
	return v.value
}

func (v *NullableCompanyMetricsDocumentsStatus) Set(val *CompanyMetricsDocumentsStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableCompanyMetricsDocumentsStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableCompanyMetricsDocumentsStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompanyMetricsDocumentsStatus(val *CompanyMetricsDocumentsStatus) *NullableCompanyMetricsDocumentsStatus {
	return &NullableCompanyMetricsDocumentsStatus{value: val, isSet: true}
}

func (v NullableCompanyMetricsDocumentsStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompanyMetricsDocumentsStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


