/*
eCF-Pronesoft Integration API

## Overview Production-grade API for issuing Electronic Tax Receipts (e-CF) in the Dominican Republic through the Pronesoft platform.  ## Authentication — OAuth 2.0 Client Credentials  ### Steps 1. Get credentials from the portal:    - Sandbox: https://ecf.sandbox.pronesoft.com -> Apps -> Default Sandbox App    - Production: https://ecf.pronesoft.com -> Integrations -> Apps -> Create App 2. Request a token via POST /oauth/token — valid for 24 hours (86400s). 3. Use: Authorization: Bearer <accessToken> on every request. 4. Renew on HTTP 401. Best practice: renew 5 minutes before expiry.  ### Multi-company delegation To act on behalf of an associated company (branch), add:   x-tenant-id: <business-uuid> Do NOT send x-tenant-id when acting as the main company.  ### Sandbox specifics - Use any RNC starting with SBX (e.g. SBX123456) — no real certificate needed. - Sequences are automatic — no need to create them manually. - The environment field in the document body MUST be TesteCF.  ### Scopes business:read, business:create, business:update, members:read, members:invite, members:revoke, certificates:read, certificates:upload, certificates:update, documents:read, documents:create, documents:send, documents:receive, documents:update, approvals:read, approvals:commercial, sequences:read, sequences:create, sequences:update, sequences:cancel, business_info:read, certification:read, certification:write, reports:read 

API version: 1.1.0
Contact: support@pronesoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ecf

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VoidTaxSequenceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VoidTaxSequenceRequest{}

// VoidTaxSequenceRequest struct for VoidTaxSequenceRequest
type VoidTaxSequenceRequest struct {
	SequenceId string `json:"sequenceId"`
	StartNumber string `json:"startNumber"`
	EndNumber string `json:"endNumber"`
	Reason string `json:"reason"`
}

type _VoidTaxSequenceRequest VoidTaxSequenceRequest

// NewVoidTaxSequenceRequest instantiates a new VoidTaxSequenceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVoidTaxSequenceRequest(sequenceId string, startNumber string, endNumber string, reason string) *VoidTaxSequenceRequest {
	this := VoidTaxSequenceRequest{}
	this.SequenceId = sequenceId
	this.StartNumber = startNumber
	this.EndNumber = endNumber
	this.Reason = reason
	return &this
}

// NewVoidTaxSequenceRequestWithDefaults instantiates a new VoidTaxSequenceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVoidTaxSequenceRequestWithDefaults() *VoidTaxSequenceRequest {
	this := VoidTaxSequenceRequest{}
	return &this
}

// GetSequenceId returns the SequenceId field value
func (o *VoidTaxSequenceRequest) GetSequenceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SequenceId
}

// GetSequenceIdOk returns a tuple with the SequenceId field value
// and a boolean to check if the value has been set.
func (o *VoidTaxSequenceRequest) GetSequenceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SequenceId, true
}

// SetSequenceId sets field value
func (o *VoidTaxSequenceRequest) SetSequenceId(v string) {
	o.SequenceId = v
}

// GetStartNumber returns the StartNumber field value
func (o *VoidTaxSequenceRequest) GetStartNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartNumber
}

// GetStartNumberOk returns a tuple with the StartNumber field value
// and a boolean to check if the value has been set.
func (o *VoidTaxSequenceRequest) GetStartNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartNumber, true
}

// SetStartNumber sets field value
func (o *VoidTaxSequenceRequest) SetStartNumber(v string) {
	o.StartNumber = v
}

// GetEndNumber returns the EndNumber field value
func (o *VoidTaxSequenceRequest) GetEndNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndNumber
}

// GetEndNumberOk returns a tuple with the EndNumber field value
// and a boolean to check if the value has been set.
func (o *VoidTaxSequenceRequest) GetEndNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndNumber, true
}

// SetEndNumber sets field value
func (o *VoidTaxSequenceRequest) SetEndNumber(v string) {
	o.EndNumber = v
}

// GetReason returns the Reason field value
func (o *VoidTaxSequenceRequest) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *VoidTaxSequenceRequest) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *VoidTaxSequenceRequest) SetReason(v string) {
	o.Reason = v
}

func (o VoidTaxSequenceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VoidTaxSequenceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sequenceId"] = o.SequenceId
	toSerialize["startNumber"] = o.StartNumber
	toSerialize["endNumber"] = o.EndNumber
	toSerialize["reason"] = o.Reason
	return toSerialize, nil
}

func (o *VoidTaxSequenceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sequenceId",
		"startNumber",
		"endNumber",
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVoidTaxSequenceRequest := _VoidTaxSequenceRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVoidTaxSequenceRequest)

	if err != nil {
		return err
	}

	*o = VoidTaxSequenceRequest(varVoidTaxSequenceRequest)

	return err
}

type NullableVoidTaxSequenceRequest struct {
	value *VoidTaxSequenceRequest
	isSet bool
}

func (v NullableVoidTaxSequenceRequest) Get() *VoidTaxSequenceRequest {
	return v.value
}

func (v *NullableVoidTaxSequenceRequest) Set(val *VoidTaxSequenceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVoidTaxSequenceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVoidTaxSequenceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVoidTaxSequenceRequest(val *VoidTaxSequenceRequest) *NullableVoidTaxSequenceRequest {
	return &NullableVoidTaxSequenceRequest{value: val, isSet: true}
}

func (v NullableVoidTaxSequenceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVoidTaxSequenceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


