/*
 * eCF-Pronesoft Master Integration API
 * Especificación de producción 100% exacta de la API de eCF-Pronesoft. **Diseñada para la generación automática de SDKs.**  Esta especificación ha sido auditada contra el código fuente real (DTOs, Controllers y Guards),  reflejando con total precisión la obligatoriedad de los campos y las estructuras de respuesta. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DiscountDetail
 */
public class DiscountDetailTest {
    private final DiscountDetail model = new DiscountDetail();

    /**
     * Model tests for DiscountDetail
     */
    @Test
    public void testDiscountDetail() {
        // TODO: test DiscountDetail
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

}
