/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.pronesoft.ecf.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accessToken 
 * @param tokenType 
 * @param expiresIn 
 */


data class OAuthTokenResponse (

    @Json(name = "accessToken")
    val accessToken: kotlin.String? = null,

    @Json(name = "tokenType")
    val tokenType: kotlin.String? = null,

    @Json(name = "expiresIn")
    val expiresIn: kotlin.Int? = null

) {


}

