/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.pronesoft.ecf.models

import com.pronesoft.ecf.models.WebhookEventType
import com.pronesoft.ecf.models.WebhookNotificationPayloadData

import com.google.gson.annotations.SerializedName

/**
 * Envelope enviado a tu URL de webhook cuando ocurre un evento. Valida la autenticidad con el header `X-Webhook-Signature: sha256=<hmac>`. Headers adicionales: `X-Webhook-Event`, `X-Webhook-ID`, `X-Webhook-Timestamp`. 
 *
 * @param id ID único de la notificación. Úsalo para deduplicar entregas.
 * @param event 
 * @param timestamp Fecha y hora del evento en ISO 8601.
 * @param businessRnc RNC de la empresa que generó el evento.
 * @param `data` 
 */


data class WebhookNotificationPayload (

    /* ID único de la notificación. Úsalo para deduplicar entregas. */
    @SerializedName("id")
    val id: kotlin.String,

    @SerializedName("event")
    val event: WebhookEventType,

    /* Fecha y hora del evento en ISO 8601. */
    @SerializedName("timestamp")
    val timestamp: java.time.OffsetDateTime,

    /* RNC de la empresa que generó el evento. */
    @SerializedName("businessRnc")
    val businessRnc: kotlin.String,

    @SerializedName("data")
    val `data`: WebhookNotificationPayloadData

) {


}

